<?php

namespace ContainerIwDR3j7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_A279dlhService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.messenger.handler_descriptor.a279dlh' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.messenger.handler_descriptor.a279dlh'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(($container->services['PrestaShop\\PrestaShop\\Adapter\\Product\\QueryHandler\\GetProductIsEnabledHandler'] ??= new \PrestaShop\PrestaShop\Adapter\Product\QueryHandler\GetProductIsEnabledHandler())->handle(...), ['method' => 'handle']);
    }
}
