<?php

namespace ContainerIwDR3j7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_H1XwmQ_Service extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.h1XwmQ.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.h1XwmQ.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'productFormBuilder' => ['services', 'prestashop.core.form.identifiable_object.builder.create_product_form_builder', 'getPrestashop_Core_Form_IdentifiableObject_Builder_CreateProductFormBuilderService', true],
            'productFormHandler' => ['services', 'prestashop.core.form.identifiable_object.product_form_handler', 'getPrestashop_Core_Form_IdentifiableObject_ProductFormHandlerService', true],
        ], [
            'productFormBuilder' => 'PrestaShop\\PrestaShop\\Core\\Form\\IdentifiableObject\\Builder\\FormBuilderInterface',
            'productFormHandler' => 'PrestaShop\\PrestaShop\\Core\\Form\\IdentifiableObject\\Handler\\FormHandlerInterface',
        ]);
    }
}
