<?php

namespace ContainerIwDR3j7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_MbOUdAService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.messenger.handler_descriptor.mbOUd_A' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.messenger.handler_descriptor.mbOUd_A'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(($container->services['prestashop.adapter.profile.permission.query_handler.get_permissions_for_configuration_handler'] ?? $container->load('getPrestashop_Adapter_Profile_Permission_QueryHandler_GetPermissionsForConfigurationHandlerService'))->handle(...), ['method' => 'handle']);
    }
}
