<?php

namespace ContainerIwDR3j7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_KGZo7tdService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.messenger.handler_descriptor.KGZo7td' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['PrestaShop\\PrestaShop\\Core\\Module\\ModuleManager'] ?? $container->load('getModuleManagerService'));

        if (isset($container->privates['.messenger.handler_descriptor.KGZo7td'])) {
            return $container->privates['.messenger.handler_descriptor.KGZo7td'];
        }
        $b = ($container->services['PrestaShop\\PrestaShop\\Core\\Module\\ModuleRepository'] ?? $container->load('getModuleRepository2Service'));

        if (isset($container->privates['.messenger.handler_descriptor.KGZo7td'])) {
            return $container->privates['.messenger.handler_descriptor.KGZo7td'];
        }

        return $container->privates['.messenger.handler_descriptor.KGZo7td'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor((new \PrestaShop\PrestaShop\Adapter\Module\CommandHandler\InstallModuleHandler($a, $b))->handle(...), ['method' => 'handle']);
    }
}
