<?php

namespace ContainerIwDR3j7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_L5gVyMzService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.L5gVyMz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.L5gVyMz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'formHandler' => ['services', 'prestashop.admin.order.invoices.by_date.form_handler', 'getPrestashop_Admin_Order_Invoices_ByDate_FormHandlerService', true],
        ], [
            'formHandler' => 'PrestaShop\\PrestaShop\\Core\\Form\\FormHandlerInterface',
        ]);
    }
}
