<?php

namespace ContainerIwDR3j7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Uv5eu4GService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.Uv5eu4G' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Uv5eu4G'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'currencyGridFactory' => ['services', 'prestashop.core.grid.factory.currency', 'getPrestashop_Core_Grid_Factory_CurrencyService', true],
            'filters' => ['privates', '.errored..service_locator.Uv5eu4G.PrestaShop\\PrestaShop\\Core\\Search\\Filters\\CurrencyFilters', NULL, 'Cannot autowire service ".service_locator.Uv5eu4G": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\CurrencyFilters" but no such service exists.'],
            'settingsFormHandler' => ['services', 'prestashop.admin.currency_settings.form_handler', 'getPrestashop_Admin_CurrencySettings_FormHandlerService', true],
        ], [
            'currencyGridFactory' => 'PrestaShop\\PrestaShop\\Core\\Grid\\GridFactoryInterface',
            'filters' => 'PrestaShop\\PrestaShop\\Core\\Search\\Filters\\CurrencyFilters',
            'settingsFormHandler' => 'PrestaShop\\PrestaShop\\Core\\Form\\FormHandlerInterface',
        ]);
    }
}
