<?php

namespace ContainerIwDR3j7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QBcciksService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.QBcciks' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QBcciks'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'filters' => ['privates', '.errored..service_locator.QBcciks.PrestaShop\\PrestaShop\\Core\\Search\\Filters\\TaxRulesGroupFilters', NULL, 'Cannot autowire service ".service_locator.QBcciks": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\TaxRulesGroupFilters" but no such service exists.'],
            'taxRulesGroupGridFactory' => ['services', 'prestashop.core.grid.factory.tax_rules_group', 'getPrestashop_Core_Grid_Factory_TaxRulesGroupService', true],
        ], [
            'filters' => 'PrestaShop\\PrestaShop\\Core\\Search\\Filters\\TaxRulesGroupFilters',
            'taxRulesGroupGridFactory' => 'PrestaShop\\PrestaShop\\Core\\Grid\\GridFactoryInterface',
        ]);
    }
}
