<?php

namespace ContainerIwDR3j7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAddressFiltersService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.15kqHjG.PrestaShop\PrestaShop\Core\Search\Filters\AddressFilters' shared service.
     *
     * @return \PrestaShop\PrestaShop\Core\Search\Filters\AddressFilters
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.15kqHjG": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\AddressFilters" but no such service exists.');
    }
}
