<?php

namespace ContainerIwDR3j7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAssignProductToCategoryHandlerService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PrestaShop\PrestaShop\Adapter\Product\CommandHandler\AssignProductToCategoryHandler' shared autowired service.
     *
     * @return \PrestaShop\PrestaShop\Adapter\Product\CommandHandler\AssignProductToCategoryHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['PrestaShop\\PrestaShop\\Adapter\\Product\\CommandHandler\\AssignProductToCategoryHandler'] = new \PrestaShop\PrestaShop\Adapter\Product\CommandHandler\AssignProductToCategoryHandler(($container->services['PrestaShop\\PrestaShop\\Adapter\\Product\\Repository\\ProductRepository'] ?? $container->load('getProductRepository3Service')));
    }
}
