<?php

namespace ContainerIwDR3j7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBackupControllerService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PrestaShopBundle\Controller\Admin\Configure\AdvancedParameters\BackupController' shared autowired service.
     *
     * @return \PrestaShopBundle\Controller\Admin\Configure\AdvancedParameters\BackupController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['PrestaShopBundle\\Controller\\Admin\\Configure\\AdvancedParameters\\BackupController'] = $instance = new \PrestaShopBundle\Controller\Admin\Configure\AdvancedParameters\BackupController();

        $instance->setContainer(($container->privates['.service_locator.YWuqMV9'] ?? $container->load('get_ServiceLocator_YWuqMV9Service'))->withContext('PrestaShopBundle\\Controller\\Admin\\Configure\\AdvancedParameters\\BackupController', $container));

        return $instance;
    }
}
