<?php

namespace ContainerIwDR3j7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCarrierValidatorService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PrestaShop\PrestaShop\Adapter\Carrier\Validate\CarrierValidator' shared autowired service.
     *
     * @return \PrestaShop\PrestaShop\Adapter\Carrier\Validate\CarrierValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['PrestaShop\\PrestaShop\\Adapter\\Carrier\\Validate\\CarrierValidator'] = new \PrestaShop\PrestaShop\Adapter\Carrier\Validate\CarrierValidator(($container->services['PrestaShop\\PrestaShop\\Adapter\\Customer\\Group\\Repository\\GroupRepository'] ??= new \PrestaShop\PrestaShop\Adapter\Customer\Group\Repository\GroupRepository()));
    }
}
