<?php

namespace ContainerIwDR3j7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHookExceptionHolderService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PrestaShop\Module\Mbo\Service\HookExceptionHolder' shared autowired service.
     *
     * @return \PrestaShop\Module\Mbo\Service\HookExceptionHolder
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['PrestaShop\\Module\\Mbo\\Service\\HookExceptionHolder'] = new \PrestaShop\Module\Mbo\Service\HookExceptionHolder();
    }
}
