<?php

namespace ContainerIwDR3j7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Adapter_DebugMode_ConfigurationService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'prestashop.adapter.debug_mode.configuration' shared service.
     *
     * @return \PrestaShop\PrestaShop\Adapter\Debug\DebugModeConfiguration
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.adapter.debug_mode.configuration'] = new \PrestaShop\PrestaShop\Adapter\Debug\DebugModeConfiguration(($container->services['prestashop.adapter.debug_mode'] ??= new \PrestaShop\PrestaShop\Adapter\Debug\DebugMode()), ($container->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] ??= new \PrestaShop\PrestaShop\Adapter\Configuration()), (\dirname(__DIR__, 5).'/config/defines.inc.php'), ($container->services['prestashop.adapter.cache.clearer.class_index_cache_clearer'] ??= new \PrestaShop\PrestaShop\Adapter\Cache\Clearer\ClassIndexCacheClearer()), ($container->services['prestashop.adapter.debug_profiling'] ??= new \PrestaShop\PrestaShop\Adapter\Debug\DebugProfiling()), ($container->services['prestashop.core.cache.clearer.cache_clearer_chain'] ?? $container->load('getPrestashop_Core_Cache_Clearer_CacheClearerChainService')));
    }
}
