<?php

namespace ContainerIwDR3j7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Adapter_Tax_CommandHandler_ToggleTaxStatusHandlerService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'prestashop.adapter.tax.command_handler.toggle_tax_status_handler' shared service.
     *
     * @return \PrestaShop\PrestaShop\Adapter\Tax\CommandHandler\ToggleTaxStatusHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.adapter.tax.command_handler.toggle_tax_status_handler'] = new \PrestaShop\PrestaShop\Adapter\Tax\CommandHandler\ToggleTaxStatusHandler();
    }
}
