<?php

namespace ContainerIwDR3j7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Admin_RequestPasswordReset_FormHandlerService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'prestashop.admin.request_password_reset.form_handler' shared service.
     *
     * @return \PrestaShop\PrestaShop\Core\Form\Handler
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['form.factory'] ?? $container->load('getForm_FactoryService'));

        if (isset($container->services['prestashop.admin.request_password_reset.form_handler'])) {
            return $container->services['prestashop.admin.request_password_reset.form_handler'];
        }

        return $container->services['prestashop.admin.request_password_reset.form_handler'] = new \PrestaShop\PrestaShop\Core\Form\Handler($a, ($container->services['PrestaShop\\PrestaShop\\Core\\Hook\\HookDispatcher'] ?? self::getHookDispatcherService($container)), new \PrestaShopBundle\Form\Admin\Login\RequestPasswordResetFormDataProvider(($container->services['prestashop.core.command_bus'] ?? $container->load('getPrestashop_Core_CommandBusService'))), 'PrestaShopBundle\\Form\\Admin\\Login\\RequestPasswordResetType', 'EmployeeRequestPasswordReset', 'request_password_reset');
    }
}
