<?php

namespace ContainerIwDR3j7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Core_ConstraintValidator_AddressZipCodeValidatorService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'prestashop.core.constraint_validator.address_zip_code_validator' shared service.
     *
     * @return \PrestaShop\PrestaShop\Core\ConstraintValidator\AddressZipCodeValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.core.constraint_validator.address_zip_code_validator'] = new \PrestaShop\PrestaShop\Core\ConstraintValidator\AddressZipCodeValidator(($container->services['Symfony\\Contracts\\Translation\\TranslatorInterface'] ?? self::getTranslatorInterfaceService($container)), ($container->services['prestashop.adapter.country.country_zip_code_requirements_provider'] ?? $container->load('getPrestashop_Adapter_Country_CountryZipCodeRequirementsProviderService')));
    }
}
