<?php

namespace ContainerIwDR3j7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Translation_SqlLoaderService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'prestashop.translation.sql_loader' shared service.
     *
     * @return \PrestaShopBundle\Translation\Loader\SqlTranslationLoader
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.translation.sql_loader'] = new \PrestaShopBundle\Translation\Loader\SqlTranslationLoader();
    }
}
