<?php

namespace ContainerIwDR3j7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Translation_Loader_DatabaseService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'prestashop.translation.loader.database' shared service.
     *
     * @return \PrestaShop\PrestaShop\Core\Translation\Storage\Loader\DatabaseTranslationLoader
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.translation.loader.database'] = new \PrestaShop\PrestaShop\Core\Translation\Storage\Loader\DatabaseTranslationLoader(($container->services['PrestaShopBundle\\Entity\\Repository\\LangRepository'] ?? self::getLangRepositoryService($container)), ($container->services['prestashop.core.admin.translation.repository'] ?? $container->load('getPrestashop_Core_Admin_Translation_RepositoryService')));
    }
}
