<?php

namespace ContainerIwDR3j7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQuantityTypeService extends AdminKernelProdContainer
{
    /*
     * Gets the private 'PrestaShopBundle\Form\Admin\Sell\Product\Stock\QuantityType' shared autowired service.
     *
     * @return \PrestaShopBundle\Form\Admin\Sell\Product\Stock\QuantityType
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['prestashop.router'] ?? $container->load('getPrestashop_RouterService'));

        if (isset($container->privates['PrestaShopBundle\\Form\\Admin\\Sell\\Product\\Stock\\QuantityType'])) {
            return $container->privates['PrestaShopBundle\\Form\\Admin\\Sell\\Product\\Stock\\QuantityType'];
        }

        return $container->privates['PrestaShopBundle\\Form\\Admin\\Sell\\Product\\Stock\\QuantityType'] = new \PrestaShopBundle\Form\Admin\Sell\Product\Stock\QuantityType(($container->services['Symfony\\Contracts\\Translation\\TranslatorInterface'] ?? self::getTranslatorInterfaceService($container)), ($container->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? self::getLegacyContextService($container))->getLanguages(), $a, ($container->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] ??= new \PrestaShop\PrestaShop\Adapter\Configuration())->getBoolean("PS_STOCK_MANAGEMENT"));
    }
}
