<?php

namespace ContainerIwDR3j7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRequiredFieldsTypeService extends AdminKernelProdContainer
{
    /*
     * Gets the private 'PrestaShopBundle\Form\Admin\Sell\Customer\RequiredFieldsType' shared autowired service.
     *
     * @return \PrestaShopBundle\Form\Admin\Sell\Customer\RequiredFieldsType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['PrestaShopBundle\\Form\\Admin\\Sell\\Customer\\RequiredFieldsType'] = new \PrestaShopBundle\Form\Admin\Sell\Customer\RequiredFieldsType(($container->services['.container.private.prestashop.core.form.choice_provider.customer_required_fields'] ?? $container->load('get_Container_Private_Prestashop_Core_Form_ChoiceProvider_CustomerRequiredFieldsService'))->getChoices());
    }
}
