<?php

namespace ContainerKctP96m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6_YOFP4Service extends AdminKernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6.YOFP4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6.YOFP4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'gridDefinitionFactory' => ['services', 'prestashop.core.grid.definition.factory.carrier', 'getPrestashop_Core_Grid_Definition_Factory_CarrierService', true],
        ], [
            'gridDefinitionFactory' => 'PrestaShop\\PrestaShop\\Core\\Grid\\Definition\\Factory\\GridDefinitionFactoryInterface',
        ]);
    }
}
