<?php

namespace ContainerKctP96m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Container_Private_Prestashop_Adapter_CheckRequirementsService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the public '.container.private.prestashop.adapter.check_requirements' shared service.
     *
     * @return \PrestaShop\PrestaShop\Adapter\Requirement\CheckRequirements
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['.container.private.prestashop.adapter.check_requirements'] = new \PrestaShop\PrestaShop\Adapter\Requirement\CheckRequirements(($container->services['Symfony\\Contracts\\Translation\\TranslatorInterface'] ?? self::getTranslatorInterfaceService($container)));
    }
}
