<?php

namespace ContainerKctP96m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0BehdUSService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0BehdUS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0BehdUS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'positionDefinitionProvider' => ['services', 'PrestaShop\\PrestaShop\\Core\\Grid\\Position\\PositionDefinitionProvider', 'getPositionDefinitionProviderService', true],
        ], [
            'positionDefinitionProvider' => 'PrestaShop\\PrestaShop\\Core\\Grid\\Position\\PositionDefinitionProvider',
        ]);
    }
}
