<?php

namespace ContainerKctP96m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiClientService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the public 'PrestaShop\Module\Mbo\Addons\ApiClient' shared autowired service.
     *
     * @return \PrestaShop\Module\Mbo\Addons\ApiClient
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['PrestaShop\\Module\\Mbo\\Addons\\ApiClient'] = $instance = new \PrestaShop\Module\Mbo\Addons\ApiClient($container->getEnv('ADDONS_API_URL'), ($container->privates['psr18.http_client'] ?? $container->load('getPsr18_HttpClientService')), ($container->privates['Psr\\Http\\Message\\ServerRequestFactoryInterface'] ??= new \Nyholm\Psr7\Factory\Psr17Factory()));

        $instance->setDefaultParams(($container->services['Symfony\\Contracts\\Translation\\TranslatorInterface'] ?? self::getTranslatorInterfaceService($container))->getLocale(), ($container->services['prestashop.adapter.data_provider.country'] ??= new \PrestaShop\PrestaShop\Adapter\Country\CountryDataProvider())->getIsoCodebyId(), ($container->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] ??= new \PrestaShop\PrestaShop\Adapter\Configuration())->get("_PS_BASE_URL_"), ($container->services['.container.private.prestashop.core.foundation.version'] ?? self::get_Container_Private_Prestashop_Core_Foundation_VersionService($container))->getSemVersion());

        return $instance;
    }
}
