<?php

namespace ContainerKctP96m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDocumentationService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the public 'PrestaShop\PrestaShop\Core\Help\Documentation' shared autowired service.
     *
     * @return \PrestaShop\PrestaShop\Core\Help\Documentation
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['PrestaShop\\PrestaShop\\Core\\Help\\Documentation'] = new \PrestaShop\PrestaShop\Core\Help\Documentation(($container->services['.container.private.prestashop.core.foundation.version'] ?? self::get_Container_Private_Prestashop_Core_Foundation_VersionService($container)), 'https://help.prestashop-project.org/');
    }
}
