<?php

namespace ContainerKctP96m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExtraModulesTypeService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the private 'PrestaShopBundle\Form\Admin\Sell\Product\ExtraModulesType' shared autowired service.
     *
     * @return \PrestaShopBundle\Form\Admin\Sell\Product\ExtraModulesType
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['PrestaShop\\PrestaShop\\Core\\Module\\ModuleRepository'] ?? $container->load('getModuleRepository2Service'));

        if (isset($container->privates['PrestaShopBundle\\Form\\Admin\\Sell\\Product\\ExtraModulesType'])) {
            return $container->privates['PrestaShopBundle\\Form\\Admin\\Sell\\Product\\ExtraModulesType'];
        }

        return $container->privates['PrestaShopBundle\\Form\\Admin\\Sell\\Product\\ExtraModulesType'] = new \PrestaShopBundle\Form\Admin\Sell\Product\ExtraModulesType(($container->services['Symfony\\Contracts\\Translation\\TranslatorInterface'] ?? self::getTranslatorInterfaceService($container)), ($container->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? self::getLegacyContextService($container))->getLanguages(), ($container->services['PrestaShop\\PrestaShop\\Core\\Hook\\HookDispatcher'] ?? self::getHookDispatcherService($container)), ($container->services['PrestaShop\\PrestaShop\\Adapter\\Module\\ModuleDataProvider'] ?? self::getModuleDataProviderService($container)), $a);
    }
}
