<?php

namespace ContainerKctP96m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getForm_FactoryService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the private 'form.factory' shared service.
     *
     * @return \Symfony\Component\Form\FormFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['form.registry'] ?? $container->load('getForm_RegistryService'));

        if (isset($container->privates['form.factory'])) {
            return $container->privates['form.factory'];
        }

        return $container->privates['form.factory'] = new \Symfony\Component\Form\FormFactory($a);
    }
}
