<?php

namespace ContainerKctP96m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderControllerService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the public 'PrestaShopBundle\Controller\Admin\Sell\Order\OrderController' shared autowired service.
     *
     * @return \PrestaShopBundle\Controller\Admin\Sell\Order\OrderController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['PrestaShopBundle\\Controller\\Admin\\Sell\\Order\\OrderController'] = $instance = new \PrestaShopBundle\Controller\Admin\Sell\Order\OrderController(($container->privates['form.factory'] ?? $container->load('getForm_FactoryService')));

        $instance->setContainer(($container->privates['.service_locator.YWuqMV9'] ?? $container->load('get_ServiceLocator_YWuqMV9Service'))->withContext('PrestaShopBundle\\Controller\\Admin\\Sell\\Order\\OrderController', $container));

        return $instance;
    }
}
