<?php

namespace ContainerKctP96m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Core_Grid_DataProvider_CustomerDiscountService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the public 'prestashop.core.grid.data_provider.customer_discount' shared service.
     *
     * @return \PrestaShop\PrestaShop\Core\Grid\Data\Factory\CustomerDiscountGridDataFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.core.grid.data_provider.customer_discount'] = new \PrestaShop\PrestaShop\Core\Grid\Data\Factory\CustomerDiscountGridDataFactory();
    }
}
