<?php

namespace ContainerKctP96m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Core_Image_Parser_ImageTagSourceParserService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the public 'prestashop.core.image.parser.image_tag_source_parser' shared service.
     *
     * @return \PrestaShop\PrestaShop\Core\Image\Parser\ImageTagSourceParser
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.core.image.parser.image_tag_source_parser'] = new \PrestaShop\PrestaShop\Core\Image\Parser\ImageTagSourceParser();
    }
}
