<?php

namespace ContainerKctP96m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Adapter_DataProvider_CarrierService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the public 'prestashop.adapter.data_provider.carrier' shared service.
     *
     * @return \PrestaShop\PrestaShop\Adapter\Carrier\CarrierDataProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.adapter.data_provider.carrier'] = new \PrestaShop\PrestaShop\Adapter\Carrier\CarrierDataProvider(($container->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] ??= new \PrestaShop\PrestaShop\Adapter\Configuration()));
    }
}
