<?php

namespace ContainerKctP96m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Translation_Manager_OriginalStringManagerService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the public 'prestashop.translation.manager.original_string_manager' shared service.
     *
     * @return \PrestaShop\TranslationToolsBundle\Translation\Manager\OriginalStringManager
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.translation.manager.original_string_manager'] = new \PrestaShop\TranslationToolsBundle\Translation\Manager\OriginalStringManager(($container->services['prestashop.translation.parser.crowdin_php_parser'] ??= new \PrestaShop\TranslationToolsBundle\Translation\Parser\CrowdinPhpParser()));
    }
}
