<?php

namespace ContainerKctP96m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPsClassicEdition_ModuleService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the public 'ps_classic_edition.module' shared service.
     *
     * @return \ps_classic_edition
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['ps_classic_edition.module'] = \Module::getInstanceByName('ps_classic_edition');
    }
}
