<?php

namespace ContainerKctP96m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Adapter_Language_CommandHandler_EditLanguageHandlerService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the public 'prestashop.adapter.language.command_handler.edit_language_handler' shared service.
     *
     * @return \PrestaShop\PrestaShop\Adapter\Language\CommandHandler\EditLanguageHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.adapter.language.command_handler.edit_language_handler'] = new \PrestaShop\PrestaShop\Adapter\Language\CommandHandler\EditLanguageHandler(($container->services['PrestaShop\\PrestaShop\\Adapter\\Image\\ImageValidator'] ?? $container->load('getImageValidatorService')));
    }
}
