<?php

namespace ContainerKctP96m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Adapter_Notification_QueryHandler_GetNotificationLastElementsHandlerService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the public 'prestashop.adapter.notification.query_handler.get_notification_last_elements_handler' shared service.
     *
     * @return \PrestaShop\PrestaShop\Adapter\Notification\QueryHandler\GetNotificationLastElementsHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.adapter.notification.query_handler.get_notification_last_elements_handler'] = new \PrestaShop\PrestaShop\Adapter\Notification\QueryHandler\GetNotificationLastElementsHandler(($container->services['prestashop.adapter.notifications.configuration'] ?? $container->load('getPrestashop_Adapter_Notifications_ConfigurationService')));
    }
}
