<?php

namespace ContainerKctP96m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Core_Currency_ExchangeRate_CircuitBreakerService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the public 'prestashop.core.currency.exchange_rate.circuit_breaker' shared service.
     *
     * @return \PrestaShop\CircuitBreaker\Contract\CircuitBreakerInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.core.currency.exchange_rate.circuit_breaker'] = ($container->services['prestashop.core.circuit_breaker.advanced_factory'] ??= new \PrestaShop\CircuitBreaker\AdvancedCircuitBreakerFactory())->create(($container->services['prestashop.core.currency.exchange_rate.settings'] ?? $container->load('getPrestashop_Core_Currency_ExchangeRate_SettingsService')));
    }
}
