<?php

namespace ContainerKctP96m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductSearchAndResetTypeService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the private 'PrestaShopBundle\Form\Admin\Sell\Product\ProductSearchAndResetType' shared autowired service.
     *
     * @return \PrestaShopBundle\Form\Admin\Sell\Product\ProductSearchAndResetType
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['prestashop.router'] ?? $container->load('getPrestashop_RouterService'));

        if (isset($container->privates['PrestaShopBundle\\Form\\Admin\\Sell\\Product\\ProductSearchAndResetType'])) {
            return $container->privates['PrestaShopBundle\\Form\\Admin\\Sell\\Product\\ProductSearchAndResetType'];
        }

        return $container->privates['PrestaShopBundle\\Form\\Admin\\Sell\\Product\\ProductSearchAndResetType'] = new \PrestaShopBundle\Form\Admin\Sell\Product\ProductSearchAndResetType($a);
    }
}
