<?php

namespace ContainerKctP96m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQuickAccessGeneratorService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the public 'PrestaShop\PrestaShop\Core\QuickAccess\QuickAccessGenerator' shared autowired service.
     *
     * @return \PrestaShop\PrestaShop\Core\QuickAccess\QuickAccessGenerator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['security.helper'] ?? self::getSecurity_HelperService($container));

        if (isset($container->services['PrestaShop\\PrestaShop\\Core\\QuickAccess\\QuickAccessGenerator'])) {
            return $container->services['PrestaShop\\PrestaShop\\Core\\QuickAccess\\QuickAccessGenerator'];
        }

        return $container->services['PrestaShop\\PrestaShop\\Core\\QuickAccess\\QuickAccessGenerator'] = new \PrestaShop\PrestaShop\Core\QuickAccess\QuickAccessGenerator(($container->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? self::getLegacyContextService($container)), ($container->privates['PrestaShop\\PrestaShop\\Core\\Context\\LanguageContext'] ?? self::getLanguageContextService($container)), ($container->privates['PrestaShop\\PrestaShop\\Core\\Context\\ShopContext'] ?? self::getShopContext2Service($container)), new \PrestaShop\PrestaShop\Adapter\QuickAccess\Repository\QuickAccessRepository(($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container)), 'ps_'), ($container->services['.container.private.prestashop.core.admin.tab.repository'] ?? self::get_Container_Private_Prestashop_Core_Admin_Tab_RepositoryService($container)), ($container->services['Symfony\\Component\\Security\\Csrf\\CsrfTokenManagerInterface'] ?? self::getCsrfTokenManagerInterfaceService($container)), ($container->privates['PrestaShop\\PrestaShop\\Core\\Context\\EmployeeContext'] ?? self::getEmployeeContextService($container)), $a);
    }
}
