<?php

namespace ContainerKctP96m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUninstaller2Service extends AdminKernelDevDebugContainer
{
    /**
     * Gets the public 'PrestaShop\Module\PsxMarketingWithGoogle\Database\Uninstaller' shared service.
     *
     * @return \PrestaShop\Module\PsxMarketingWithGoogle\Database\Uninstaller
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['PrestaShop\\Module\\PsxMarketingWithGoogle\\Database\\Uninstaller'] = new \PrestaShop\Module\PsxMarketingWithGoogle\Database\Uninstaller(($container->services['PrestaShop\\Module\\PsxMarketingWithGoogle\\Repository\\TabRepository'] ??= new \PrestaShop\Module\PsxMarketingWithGoogle\Repository\TabRepository()), ($container->services['PrestaShop\\Module\\PsxMarketingWithGoogle\\Tracker\\Segment'] ?? $container->load('getSegment2Service')), ($container->services['PrestaShop\\Module\\PsxMarketingWithGoogle\\Handler\\ErrorHandler'] ??= new \PrestaShop\Module\PsxMarketingWithGoogle\Handler\ErrorHandler()));
    }
}
