<?php

namespace ContainerXrLzW05;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_UZjMLI2Service extends AdminKernelProdContainer
{
    /*
     * Gets the private '.messenger.handler_descriptor.uZjMLI2' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.messenger.handler_descriptor.uZjMLI2'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor((new \PrestaShop\PrestaShop\Adapter\ApiClient\CommandHandler\ForceApiClientSecretHandler(($container->services['PrestaShopBundle\\Entity\\Repository\\ApiClientRepository'] ?? self::getApiClientRepositoryService($container)), ($container->services['Symfony\\Component\\PasswordHasher\\PasswordHasherInterface'] ?? $container->load('getPasswordHasherInterfaceService'))))->handle(...), ['method' => 'handle']);
    }
}
