<?php

namespace ContainerXrLzW05;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_NG4MWDJService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.messenger.handler_descriptor.NG4MWDJ' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.messenger.handler_descriptor.NG4MWDJ'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(($container->services['prestashop.adapter.manufacturer.command_handler.edit_manufacturer_handler'] ??= new \PrestaShop\PrestaShop\Adapter\Manufacturer\CommandHandler\EditManufacturerHandler())->handle(...), ['method' => 'handle']);
    }
}
