<?php

namespace ContainerXrLzW05;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Adapter_Category_CommandHandler_DeleteCategoryHandlerService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'prestashop.adapter.category.command_handler.delete_category_handler' shared service.
     *
     * @return \PrestaShop\PrestaShop\Adapter\Category\CommandHandler\DeleteCategoryHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.adapter.category.command_handler.delete_category_handler'] = new \PrestaShop\PrestaShop\Adapter\Category\CommandHandler\DeleteCategoryHandler(($container->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? self::getLegacyContextService($container))->getContext()->shop->id_category, ($container->services['PrestaShop\\PrestaShop\\Adapter\\Product\\Repository\\ProductRepository'] ?? $container->load('getProductRepository3Service')), ($container->services['PrestaShop\\PrestaShop\\Adapter\\Category\\Repository\\CategoryRepository'] ?? $container->load('getCategoryRepository2Service')));
    }
}
