<?php

namespace ContainerXrLzW05;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Admin_Import_FormHandlerService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'prestashop.admin.import.form_handler' shared service.
     *
     * @return \PrestaShopBundle\Form\Admin\Configure\AdvancedParameters\Import\ImportFormHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['prestashop.admin.import.form_builder'] ?? $container->load('getPrestashop_Admin_Import_FormBuilderService'));

        if (isset($container->services['prestashop.admin.import.form_handler'])) {
            return $container->services['prestashop.admin.import.form_handler'];
        }

        return $container->services['prestashop.admin.import.form_handler'] = new \PrestaShopBundle\Form\Admin\Configure\AdvancedParameters\Import\ImportFormHandler($a, ($container->services['PrestaShop\\PrestaShop\\Core\\Hook\\HookDispatcher'] ?? self::getHookDispatcherService($container)), ($container->services['prestashop.admin.import.form_data_provider'] ?? $container->load('getPrestashop_Admin_Import_FormDataProviderService')), 'Import');
    }
}
