<?php

namespace ContainerXrLzW05;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductCommentCriterionFormDataProviderService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'product_comment_criterion_form_data_provider' shared service.
     *
     * @return \PrestaShop\Module\ProductComment\Form\ProductCommentCriterionFormDataProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['product_comment_criterion_form_data_provider'] = new \PrestaShop\Module\ProductComment\Form\ProductCommentCriterionFormDataProvider(($container->services['product_comment_criterion_repository'] ?? $container->load('getProductCommentCriterionRepositoryService')), ($container->services['PrestaShopBundle\\Entity\\Repository\\LangRepository'] ?? self::getLangRepositoryService($container)));
    }
}
