<?php

namespace ContainerXrLzW05;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Adapter_Order_CommandHandler_AddOrderFromBackOfficeHandlerService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'prestashop.adapter.order.command_handler.add_order_from_back_office_handler' shared service.
     *
     * @return \PrestaShop\PrestaShop\Adapter\Order\CommandHandler\AddOrderFromBackOfficeHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.adapter.order.command_handler.add_order_from_back_office_handler'] = new \PrestaShop\PrestaShop\Adapter\Order\CommandHandler\AddOrderFromBackOfficeHandler(($container->services['PrestaShop\\PrestaShop\\Adapter\\ContextStateManager'] ?? self::getContextStateManagerService($container)));
    }
}
