<?php

namespace ContainerXrLzW05;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Core_Currency_ExchangeRate_SettingsService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'prestashop.core.currency.exchange_rate.settings' shared service.
     *
     * @return \PrestaShop\CircuitBreaker\FactorySettings
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['prestashop.core.currency.exchange_rate.settings'] = $instance = new \PrestaShop\CircuitBreaker\FactorySettings(3, 1, 3600);

        $instance->setStrippedFailures(3);
        $instance->setStrippedTimeout(2);
        $instance->setStorage(($container->services['prestashop.core.circuit_breaker.storage'] ?? $container->load('getPrestashop_Core_CircuitBreaker_StorageService')));

        return $instance;
    }
}
