<?php

namespace ContainerXrLzW05;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Admin_TranslationsSettings_ExportCatalogues_FormHandlerService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'prestashop.admin.translations_settings.export_catalogues.form_handler' shared service.
     *
     * @return \PrestaShopBundle\Form\Admin\Improve\International\Translations\TranslationsSettingsFormHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['form.factory'] ?? $container->load('getForm_FactoryService'));

        if (isset($container->services['prestashop.admin.translations_settings.export_catalogues.form_handler'])) {
            return $container->services['prestashop.admin.translations_settings.export_catalogues.form_handler'];
        }

        return $container->services['prestashop.admin.translations_settings.export_catalogues.form_handler'] = new \PrestaShopBundle\Form\Admin\Improve\International\Translations\TranslationsSettingsFormHandler($a, ($container->services['PrestaShop\\PrestaShop\\Core\\Hook\\HookDispatcher'] ?? self::getHookDispatcherService($container)), 'PrestaShopBundle\\Form\\Admin\\Improve\\International\\Translations\\ExportCataloguesType', 'TranslationSettingsPageExportCatalogues');
    }
}
