<?php

namespace ContainerXrLzW05;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Admin_ProductPreferences_Page_DataProviderService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'prestashop.admin.product_preferences.page.data_provider' shared service.
     *
     * @return \PrestaShopBundle\Form\Admin\Configure\ShopParameters\ProductPreferences\PageFormDataProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.admin.product_preferences.page.data_provider'] = new \PrestaShopBundle\Form\Admin\Configure\ShopParameters\ProductPreferences\PageFormDataProvider(($container->services['prestashop.adapter.product_page.configuration'] ?? $container->load('getPrestashop_Adapter_ProductPage_ConfigurationService')));
    }
}
