<?php

namespace ContainerXrLzW05;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Adapter_Language_QueryHandler_GetLanguageForEditingService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'prestashop.adapter.language.query_handler.get_language_for_editing' shared service.
     *
     * @return \PrestaShop\PrestaShop\Adapter\Language\QueryHandler\GetLanguageForEditingHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.adapter.language.query_handler.get_language_for_editing'] = new \PrestaShop\PrestaShop\Adapter\Language\QueryHandler\GetLanguageForEditingHandler();
    }
}
