<?php

namespace ContainerXrLzW05;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Core_Form_IdentifiableObject_DataProvider_CustomerFormDataProviderService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'prestashop.core.form.identifiable_object.data_provider.customer_form_data_provider' shared service.
     *
     * @return \PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataProvider\CustomerFormDataProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['prestashop.core.query_bus'] ?? $container->load('getPrestashop_Core_QueryBusService'));

        if (isset($container->services['prestashop.core.form.identifiable_object.data_provider.customer_form_data_provider'])) {
            return $container->services['prestashop.core.form.identifiable_object.data_provider.customer_form_data_provider'];
        }

        return $container->services['prestashop.core.form.identifiable_object.data_provider.customer_form_data_provider'] = new \PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataProvider\CustomerFormDataProvider($a, ($container->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] ??= new \PrestaShop\PrestaShop\Adapter\Configuration()), ($container->services['prestashop.adapter.group.provider.default_groups_provider'] ?? $container->load('getPrestashop_Adapter_Group_Provider_DefaultGroupsProviderService')), ($container->services['.container.private.prestashop.core.b2b.b2b_feature'] ?? $container->load('get_Container_Private_Prestashop_Core_B2b_B2bFeatureService'))->isActive());
    }
}
