<?php

namespace ContainerKctP96m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HzUiRzoService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hzUiRzo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hzUiRzo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'iniConfiguration' => ['services', 'PrestaShop\\PrestaShop\\Core\\Configuration\\IniConfiguration', 'getIniConfigurationService', true],
        ], [
            'iniConfiguration' => 'PrestaShop\\PrestaShop\\Core\\Configuration\\IniConfiguration',
        ]);
    }
}
