<?php

namespace ContainerKctP96m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ToqbzOOService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.toqbzOO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.toqbzOO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'langRepository' => ['services', 'PrestaShopBundle\\Entity\\Repository\\LangRepository', 'getLangRepositoryService', false],
            'themeExporter' => ['services', 'prestashop.translation.theme.exporter', 'getPrestashop_Translation_Theme_ExporterService', true],
        ], [
            'langRepository' => '?',
            'themeExporter' => 'PrestaShopBundle\\Translation\\Exporter\\ThemeExporter',
        ]);
    }
}
