<?php

namespace ContainerKctP96m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Container_Private_Prestashop_Core_Form_ChoiceProvider_TimezoneByNameService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the public '.container.private.prestashop.core.form.choice_provider.timezone_by_name' shared autowired service.
     *
     * @return \PrestaShop\PrestaShop\Core\Form\ChoiceProvider\TimezoneByNameChoiceProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['.container.private.prestashop.core.form.choice_provider.timezone_by_name'] = new \PrestaShop\PrestaShop\Core\Form\ChoiceProvider\TimezoneByNameChoiceProvider(($container->services['prestashop.core.admin.timezone.repository'] ?? $container->load('getPrestashop_Core_Admin_Timezone_RepositoryService')));
    }
}
