<?php

namespace ContainerKctP96m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_3IOFFN9Service extends AdminKernelDevDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.3IOFFN9' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.messenger.handler_descriptor.3IOFFN9'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(($container->services['prestashop.adapter.command_handler.add_customization_handler'] ??= new \PrestaShop\PrestaShop\Adapter\Cart\CommandHandler\AddCustomizationHandler())->handle(...), ['method' => 'handle']);
    }
}
