<?php

namespace ContainerKctP96m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ft8sYjoService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ft8sYjo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ft8sYjo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'formBuilder' => ['services', 'prestashop.core.form.identifiable_object.builder.order_message_form_builder', 'getPrestashop_Core_Form_IdentifiableObject_Builder_OrderMessageFormBuilderService', true],
            'formHandler' => ['services', 'prestashop.core.form.identifiable_object.handler.order_message_form_handler', 'getPrestashop_Core_Form_IdentifiableObject_Handler_OrderMessageFormHandlerService', true],
            'multiStoreFeature' => ['services', 'PrestaShop\\PrestaShop\\Adapter\\Feature\\MultistoreFeature', 'getMultistoreFeatureService', false],
        ], [
            'formBuilder' => 'PrestaShop\\PrestaShop\\Core\\Form\\IdentifiableObject\\Builder\\FormBuilderInterface',
            'formHandler' => 'PrestaShop\\PrestaShop\\Core\\Form\\IdentifiableObject\\Handler\\FormHandlerInterface',
            'multiStoreFeature' => 'PrestaShop\\PrestaShop\\Adapter\\Feature\\MultistoreFeature',
        ]);
    }
}
