<?php

namespace ContainerKctP96m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YLsydXzService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yLsydXz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yLsydXz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'filters' => ['privates', '.errored..service_locator.yLsydXz.PrestaShop\\PrestaShop\\Core\\Search\\Filters\\Security\\Session\\CustomerFilters', NULL, 'Cannot autowire service ".service_locator.yLsydXz": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\Security\\Session\\CustomerFilters" but no such service exists.'],
            'sessionsCustomersGridFactory' => ['services', 'prestashop.core.grid.factory.security.session.customer', 'getPrestashop_Core_Grid_Factory_Security_Session_CustomerService', true],
        ], [
            'filters' => 'PrestaShop\\PrestaShop\\Core\\Search\\Filters\\Security\\Session\\CustomerFilters',
            'sessionsCustomersGridFactory' => 'PrestaShop\\PrestaShop\\Core\\Grid\\GridFactoryInterface',
        ]);
    }
}
