<?php

namespace ContainerKctP96m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Debug_Security_Voter_Prestashop_Security_Voter_ProductService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the private '.debug.security.voter.prestashop.security.voter.product' shared service.
     *
     * @return \Symfony\Component\Security\Core\Authorization\Voter\TraceableVoter
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->privates['.debug.security.voter.prestashop.security.voter.product'])) {
            return $container->privates['.debug.security.voter.prestashop.security.voter.product'];
        }

        return $container->privates['.debug.security.voter.prestashop.security.voter.product'] = new \Symfony\Component\Security\Core\Authorization\Voter\TraceableVoter(new \PrestaShopBundle\Security\Voter\PageVoter(new \PrestaShop\PrestaShop\Adapter\Security\Access()), $a);
    }
}
