<?php

namespace ContainerKctP96m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBasicInformationFillerService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the public 'PrestaShop\PrestaShop\Adapter\Product\Update\Filler\BasicInformationFiller' shared service.
     *
     * @return \PrestaShop\PrestaShop\Adapter\Product\Update\Filler\BasicInformationFiller
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['PrestaShop\\PrestaShop\\Adapter\\Product\\Update\\Filler\\BasicInformationFiller'] = new \PrestaShop\PrestaShop\Adapter\Product\Update\Filler\BasicInformationFiller(($container->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] ??= new \PrestaShop\PrestaShop\Adapter\Configuration())->get("PS_LANG_DEFAULT"));
    }
}
