<?php

namespace ContainerKctP96m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDatePickerTypeService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the private 'PrestaShopBundle\Form\Admin\Type\DatePickerType' shared autowired service.
     *
     * @return \PrestaShopBundle\Form\Admin\Type\DatePickerType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['PrestaShopBundle\\Form\\Admin\\Type\\DatePickerType'] = new \PrestaShopBundle\Form\Admin\Type\DatePickerType(($container->services['.container.private.prestashop.bundle.form.data_transformer.arabic_to_latin_digit'] ?? $container->load('get_Container_Private_Prestashop_Bundle_Form_DataTransformer_ArabicToLatinDigitService')));
    }
}
