<?php

namespace ContainerKctP96m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeleteCategoryThumbnailImageHandlerService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the public 'PrestaShop\PrestaShop\Adapter\Category\CommandHandler\DeleteCategoryThumbnailImageHandler' shared service.
     *
     * @return \PrestaShop\PrestaShop\Adapter\Category\CommandHandler\DeleteCategoryThumbnailImageHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['PrestaShop\\PrestaShop\\Adapter\\Category\\CommandHandler\\DeleteCategoryThumbnailImageHandler'] = new \PrestaShop\PrestaShop\Adapter\Category\CommandHandler\DeleteCategoryThumbnailImageHandler(($container->privates['filesystem'] ??= new \Symfony\Component\Filesystem\Filesystem()), ($container->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] ??= new \PrestaShop\PrestaShop\Adapter\Configuration()));
    }
}
