<?php

namespace ContainerKctP96m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmployeeFiltersService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.6LQaMAE.PrestaShop\PrestaShop\Core\Search\Filters\EmployeeFilters' shared service.
     *
     * @return \PrestaShop\PrestaShop\Core\Search\Filters\EmployeeFilters
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.6LQaMAE": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\EmployeeFilters" but no such service exists.');
    }
}
