<?php

namespace ContainerKctP96m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFeatureValueFiltersService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator..ORNjuw.PrestaShop\PrestaShop\Core\Search\Filters\FeatureValueFilters' shared service.
     *
     * @return \PrestaShop\PrestaShop\Core\Search\Filters\FeatureValueFilters
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator..ORNjuw": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\FeatureValueFilters" but no such service exists.');
    }
}
