<?php

namespace ContainerKctP96m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFeatureValueGridFactoryService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the public 'PrestaShop\PrestaShop\Core\Grid\Factory\FeatureValueGridFactory' shared autowired service.
     *
     * @return \PrestaShop\PrestaShop\Core\Grid\Factory\FeatureValueGridFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['PrestaShop\\PrestaShop\\Core\\Grid\\Factory\\FeatureValueGridFactory'] = new \PrestaShop\PrestaShop\Core\Grid\Factory\FeatureValueGridFactory(($container->services['PrestaShop\\PrestaShop\\Core\\Grid\\Definition\\Factory\\FeatureValueGridDefinitionFactory'] ?? $container->load('getFeatureValueGridDefinitionFactoryService')), ($container->services['prestashop.core.grid.data.factory.feature_value'] ?? $container->load('getPrestashop_Core_Grid_Data_Factory_FeatureValueService')), ($container->services['.container.private.prestashop.core.grid.filter.form_factory'] ?? $container->load('get_Container_Private_Prestashop_Core_Grid_Filter_FormFactoryService')), ($container->services['PrestaShop\\PrestaShop\\Core\\Hook\\HookDispatcher'] ?? self::getHookDispatcherService($container)), ($container->privates['PrestaShop\\PrestaShop\\Adapter\\Feature\\Repository\\FeatureRepository'] ?? $container->load('getFeatureRepositoryService')), ($container->services['Symfony\\Contracts\\Translation\\TranslatorInterface'] ?? self::getTranslatorInterfaceService($container)));
    }
}
