<?php

namespace ContainerKctP96m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImageSettingsTypeService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the private 'PrestaShopBundle\Form\Admin\Improve\Design\ImageSettings\ImageSettingsType' shared autowired service.
     *
     * @return \PrestaShopBundle\Form\Admin\Improve\Design\ImageSettings\ImageSettingsType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['PrestaShopBundle\\Form\\Admin\\Improve\\Design\\ImageSettings\\ImageSettingsType'] = new \PrestaShopBundle\Form\Admin\Improve\Design\ImageSettings\ImageSettingsType(($container->services['Symfony\\Contracts\\Translation\\TranslatorInterface'] ?? self::getTranslatorInterfaceService($container)), ($container->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? self::getLegacyContextService($container))->getLanguages(), ($container->services['PrestaShop\\PrestaShop\\Core\\Image\\AvifExtensionChecker'] ??= new \PrestaShop\PrestaShop\Core\Image\AvifExtensionChecker()));
    }
}
