<?php

namespace ContainerKctP96m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLegacyControllerService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the public 'PrestaShopBundle\Controller\Admin\LegacyController' shared autowired service.
     *
     * @return \PrestaShopBundle\Controller\Admin\LegacyController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['PrestaShopBundle\\Controller\\Admin\\LegacyController'] = $instance = new \PrestaShopBundle\Controller\Admin\LegacyController(($container->services['.container.private.prestashop.core.admin.tab.repository'] ?? self::get_Container_Private_Prestashop_Core_Admin_Tab_RepositoryService($container)), ($container->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? self::getLegacyContextService($container)), ($container->privates['PrestaShopBundle\\Twig\\Layout\\SmartyVariablesFiller'] ?? self::getSmartyVariablesFillerService($container)), ($container->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] ??= new \PrestaShop\PrestaShop\Adapter\Configuration()), ($container->privates['PrestaShopBundle\\Twig\\Layout\\MenuBuilder'] ?? self::getMenuBuilderService($container)));

        $instance->setContainer(($container->privates['.service_locator.YWuqMV9'] ?? $container->load('get_ServiceLocator_YWuqMV9Service'))->withContext('PrestaShopBundle\\Controller\\Admin\\LegacyController', $container));

        return $instance;
    }
}
