<?php

namespace ContainerKctP96m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Admin_TaxOptions_FormDataProviderService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the public 'prestashop.admin.tax_options.form_data_provider' shared service.
     *
     * @return \PrestaShopBundle\Form\Admin\Improve\International\Tax\TaxOptionsFormDataProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.admin.tax_options.form_data_provider'] = new \PrestaShopBundle\Form\Admin\Improve\International\Tax\TaxOptionsFormDataProvider(($container->services['prestashop.core.tax.tax_options_configuration'] ?? $container->load('getPrestashop_Core_Tax_TaxOptionsConfigurationService')));
    }
}
