<?php

namespace ContainerKctP96m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Adapter_Performance_DebugMode_FormHandlerService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the public 'prestashop.adapter.performance.debug_mode.form_handler' shared service.
     *
     * @return \PrestaShop\PrestaShop\Core\Form\Handler
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['form.factory'] ?? $container->load('getForm_FactoryService'));

        if (isset($container->services['prestashop.adapter.performance.debug_mode.form_handler'])) {
            return $container->services['prestashop.adapter.performance.debug_mode.form_handler'];
        }

        return $container->services['prestashop.adapter.performance.debug_mode.form_handler'] = new \PrestaShop\PrestaShop\Core\Form\Handler($a, ($container->services['PrestaShop\\PrestaShop\\Core\\Hook\\HookDispatcher'] ?? self::getHookDispatcherService($container)), ($container->services['prestashop.adapter.performance.debug_mode.form_provider'] ?? $container->load('getPrestashop_Adapter_Performance_DebugMode_FormProviderService')), 'PrestaShopBundle\\Form\\Admin\\AdvancedParameters\\Performance\\DebugModeType', 'PerformancePageDebugMode', 'debug_mode');
    }
}
