<?php

namespace ContainerKctP96m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Adapter_Import_FileOpenerService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the public 'prestashop.adapter.import.file_opener' shared service.
     *
     * @return \PrestaShop\PrestaShop\Adapter\Import\CsvFileOpener
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.adapter.import.file_opener'] = new \PrestaShop\PrestaShop\Adapter\Import\CsvFileOpener(($container->services['prestashop.adapter.import.excel_to_csv_converter'] ?? $container->load('getPrestashop_Adapter_Import_ExcelToCsvConverterService')));
    }
}
