<?php

namespace ContainerKctP96m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPsCheckout_DbService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the public 'ps_checkout.db' shared autowired service.
     *
     * @return \Db
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['ps_checkout.db'] = \Db::getInstance();
    }
}
