<?php

namespace ContainerKctP96m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Core_Grid_Factory_LanguageDecoratorService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the public 'prestashop.core.grid.factory.language_decorator' shared service.
     *
     * @return \PrestaShop\PrestaShop\Core\Grid\Data\Factory\LanguageGridDataFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.core.grid.factory.language_decorator'] = new \PrestaShop\PrestaShop\Core\Grid\Data\Factory\LanguageGridDataFactory(($container->services['prestashop.core.grid.data.factory.language'] ?? $container->load('getPrestashop_Core_Grid_Data_Factory_LanguageService')), ($container->services['prestashop.adapter.language.language_flag_thumbnail_provider'] ?? $container->load('getPrestashop_Adapter_Language_LanguageFlagThumbnailProviderService')));
    }
}
