<?php

namespace ContainerKctP96m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaymentMethodsControllerService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the public 'PrestaShopBundle\Controller\Admin\Improve\Payment\PaymentMethodsController' shared autowired service.
     *
     * @return \PrestaShopBundle\Controller\Admin\Improve\Payment\PaymentMethodsController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['PrestaShopBundle\\Controller\\Admin\\Improve\\Payment\\PaymentMethodsController'] = $instance = new \PrestaShopBundle\Controller\Admin\Improve\Payment\PaymentMethodsController();

        $instance->setContainer(($container->privates['.service_locator.YWuqMV9'] ?? $container->load('get_ServiceLocator_YWuqMV9Service'))->withContext('PrestaShopBundle\\Controller\\Admin\\Improve\\Payment\\PaymentMethodsController', $container));

        return $instance;
    }
}
