<?php

namespace ContainerKctP96m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Adapter_Cart_CommandHandler_UpdateCartCurrencyHandlerService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the public 'prestashop.adapter.cart.command_handler.update_cart_currency_handler' shared service.
     *
     * @return \PrestaShop\PrestaShop\Adapter\Cart\CommandHandler\UpdateCartCurrencyHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.adapter.cart.command_handler.update_cart_currency_handler'] = new \PrestaShop\PrestaShop\Adapter\Cart\CommandHandler\UpdateCartCurrencyHandler();
    }
}
