<?php

namespace ContainerKctP96m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Adapter_Meta_QueryHandler_GetMetaForEditingService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the public 'prestashop.adapter.meta.query_handler.get_meta_for_editing' shared service.
     *
     * @return \PrestaShop\PrestaShop\Adapter\Meta\QueryHandler\GetMetaForEditingHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.adapter.meta.query_handler.get_meta_for_editing'] = new \PrestaShop\PrestaShop\Adapter\Meta\QueryHandler\GetMetaForEditingHandler();
    }
}
