<?php

namespace ContainerKctP96m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductAttachmentUpdaterService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the private 'PrestaShop\PrestaShop\Adapter\Product\Update\ProductAttachmentUpdater' shared autowired service.
     *
     * @return \PrestaShop\PrestaShop\Adapter\Product\Update\ProductAttachmentUpdater
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['PrestaShop\\PrestaShop\\Adapter\\Product\\Update\\ProductAttachmentUpdater'] = new \PrestaShop\PrestaShop\Adapter\Product\Update\ProductAttachmentUpdater(($container->services['PrestaShop\\PrestaShop\\Adapter\\Product\\Repository\\ProductRepository'] ?? $container->load('getProductRepository3Service')), ($container->services['PrestaShop\\PrestaShop\\Adapter\\Attachment\\AttachmentRepository'] ?? $container->load('getAttachmentRepositoryService')));
    }
}
