<?php

namespace ContainerIwDR3j7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HFLQYQfService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.HFLQYQf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HFLQYQf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kpiRow' => ['privates', '.errored..service_locator.HFLQYQf.PrestaShop\\PrestaShop\\Core\\Kpi\\Row\\KpiRowInterface', NULL, 'Cannot autowire service ".service_locator.HFLQYQf": it references interface "PrestaShop\\PrestaShop\\Core\\Kpi\\Row\\KpiRowInterface" but no such service exists. Did you create a class that implements this interface?'],
            'kpiRowPresenter' => ['services', '.container.private.prestashop.core.kpi_row.presenter', 'get_Container_Private_Prestashop_Core_KpiRow_PresenterService', true],
        ], [
            'kpiRow' => 'PrestaShop\\PrestaShop\\Core\\Kpi\\Row\\KpiRowInterface',
            'kpiRowPresenter' => '?',
        ]);
    }
}
