<?php

namespace ContainerIwDR3j7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NhpNhYrService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.nhpNhYr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nhpNhYr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'bulkFormBuilder' => ['services', 'prestashop.core.form.identifiable_object.builder.bulk_combination_form_builder', 'getPrestashop_Core_Form_IdentifiableObject_Builder_BulkCombinationFormBuilderService', true],
        ], [
            'bulkFormBuilder' => 'PrestaShop\\PrestaShop\\Core\\Form\\IdentifiableObject\\Builder\\FormBuilderInterface',
        ]);
    }
}
