<?php

namespace ContainerIwDR3j7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_YxsTzHxService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.messenger.handler_descriptor.YxsTzHx' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.messenger.handler_descriptor.YxsTzHx'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(($container->services['prestashop.core.domain.customer_service.command_handler.forward_customer_thread_handler'] ?? $container->load('getPrestashop_Core_Domain_CustomerService_CommandHandler_ForwardCustomerThreadHandlerService'))->handle(...), ['method' => 'handle']);
    }
}
