<?php

namespace ContainerIwDR3j7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_RQrg10Service extends AdminKernelProdContainer
{
    /*
     * Gets the private '.messenger.handler_descriptor.rQrg10_' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.messenger.handler_descriptor.rQrg10_'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(($container->services['prestashop.adapter.zone.command_handler.bulk_delete_zone_handler'] ??= new \PrestaShop\PrestaShop\Adapter\Zone\CommandHandler\BulkDeleteZoneHandler())->handle(...), ['method' => 'handle']);
    }
}
