<?php

namespace ContainerIwDR3j7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Container_Private_Form_Type_Extension_ResizableTextService extends AdminKernelProdContainer
{
    /*
     * Gets the public '.container.private.form.type.extension.resizable_text' shared autowired service.
     *
     * @return \PrestaShopBundle\Form\Extension\ResizableTextTypeExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['.container.private.form.type.extension.resizable_text'] = new \PrestaShopBundle\Form\Extension\ResizableTextTypeExtension();
    }
}
