<?php

namespace ContainerIwDR3j7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoriesProviderBuilderService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PrestaShop\PrestaShop\Adapter\Category\CategoriesProviderBuilder' shared service.
     *
     * @return \PrestaShop\PrestaShop\Adapter\Category\CategoriesProviderBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['PrestaShop\\PrestaShop\\Adapter\\Category\\CategoriesProviderBuilder'] = new \PrestaShop\PrestaShop\Adapter\Category\CategoriesProviderBuilder(($container->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? self::getLegacyContextService($container)), ($container->services['prestashop.core.addon.theme.repository'] ?? $container->load('getPrestashop_Core_Addon_Theme_RepositoryService')), (\dirname(__DIR__, 2).'/'), \dirname(__DIR__, 5), '/app/config/addons/categories.yml');
    }
}
