<?php

namespace ContainerIwDR3j7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGeneralSettingsService extends AdminKernelProdContainer
{
    /*
     * Gets the private 'PrestaShopBundle\Form\Admin\Improve\Shipping\Carrier\GeneralSettings' shared autowired service.
     *
     * @return \PrestaShopBundle\Form\Admin\Improve\Shipping\Carrier\GeneralSettings
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['PrestaShopBundle\\Form\\Admin\\Improve\\Shipping\\Carrier\\GeneralSettings'] = new \PrestaShopBundle\Form\Admin\Improve\Shipping\Carrier\GeneralSettings(($container->services['Symfony\\Contracts\\Translation\\TranslatorInterface'] ?? self::getTranslatorInterfaceService($container)), ($container->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? self::getLegacyContextService($container))->getLanguages(), ($container->services['.container.private.prestashop.core.form.choice_provider.group_by_id'] ?? $container->load('get_Container_Private_Prestashop_Core_Form_ChoiceProvider_GroupByIdService')));
    }
}
