<?php

namespace ContainerIwDR3j7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Core_Grid_Factory_EmailLogsService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'prestashop.core.grid.factory.email_logs' shared service.
     *
     * @return \PrestaShop\PrestaShop\Core\Grid\GridFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.core.grid.factory.email_logs'] = new \PrestaShop\PrestaShop\Core\Grid\GridFactory(($container->services['prestashop.core.grid.definition.factory.email_logs'] ?? $container->load('getPrestashop_Core_Grid_Definition_Factory_EmailLogsService')), ($container->services['prestashop.core.grid.data_factory.email_logs'] ?? $container->load('getPrestashop_Core_Grid_DataFactory_EmailLogsService')), ($container->services['.container.private.prestashop.core.grid.filter.form_factory'] ?? $container->load('get_Container_Private_Prestashop_Core_Grid_Filter_FormFactoryService')), ($container->services['PrestaShop\\PrestaShop\\Core\\Hook\\HookDispatcher'] ?? self::getHookDispatcherService($container)));
    }
}
