<?php

namespace ContainerIwDR3j7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Adapter_Performance_OptionalFeatures_FormProviderService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'prestashop.adapter.performance.optional_features.form_provider' shared service.
     *
     * @return \PrestaShopBundle\Form\Admin\AdvancedParameters\Performance\PerformanceFormDataProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.adapter.performance.optional_features.form_provider'] = new \PrestaShopBundle\Form\Admin\AdvancedParameters\Performance\PerformanceFormDataProvider(($container->services['prestashop.adapter.optional_features.configuration'] ?? $container->load('getPrestashop_Adapter_OptionalFeatures_ConfigurationService')));
    }
}
