<?php

namespace ContainerIwDR3j7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Admin_Geolocation_Options_FormDataProviderService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'prestashop.admin.geolocation.options.form_data_provider' shared service.
     *
     * @return \PrestaShopBundle\Form\Admin\Improve\International\Geolocation\GeolocationOptionsFormDataProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.admin.geolocation.options.form_data_provider'] = new \PrestaShopBundle\Form\Admin\Improve\International\Geolocation\GeolocationOptionsFormDataProvider(($container->services['prestashop.adapter.geolocation_options.configuration'] ?? $container->load('getPrestashop_Adapter_GeolocationOptions_ConfigurationService')));
    }
}
