<?php

namespace ContainerIwDR3j7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Core_Grid_Query_WebserviceKeyService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'prestashop.core.grid.query.webservice_key' shared service.
     *
     * @return \PrestaShop\PrestaShop\Core\Grid\Query\WebserviceKeyQueryBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.core.grid.query.webservice_key'] = new \PrestaShop\PrestaShop\Core\Grid\Query\WebserviceKeyQueryBuilder(($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container)), 'ps_', ($container->services['PrestaShop\\PrestaShop\\Core\\Grid\\Query\\DoctrineSearchCriteriaApplicatorInterface'] ??= new \PrestaShop\PrestaShop\Core\Grid\Query\DoctrineSearchCriteriaApplicator()), ($container->services['.container.private.prestashop.adapter.shop.context'] ??= new \PrestaShop\PrestaShop\Adapter\Shop\Context())->getContextListShopID(), ($container->services['PrestaShop\\PrestaShop\\Core\\Grid\\Query\\Filter\\DoctrineFilterApplicatorInterface'] ??= new \PrestaShop\PrestaShop\Core\Grid\Query\Filter\DoctrineFilterApplicator()));
    }
}
