<?php

namespace ContainerIwDR3j7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPsFacebook_CurrencyService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'ps_facebook.currency' shared service.
     *
     * @return \Currency
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['ps_facebook.currency'] = \PrestaShop\Module\PrestashopFacebook\Factory\ContextFactory::getCurrency();
    }
}
