<?php

namespace ContainerIwDR3j7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Adapter_DataProvider_OrderReturnStateService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'prestashop.adapter.data_provider.order_return_state' shared service.
     *
     * @return \PrestaShop\PrestaShop\Adapter\OrderReturnState\OrderReturnStateDataProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.adapter.data_provider.order_return_state'] = new \PrestaShop\PrestaShop\Adapter\OrderReturnState\OrderReturnStateDataProvider();
    }
}
