<?php

namespace ContainerIwDR3j7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Adapter_MailingInformationService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'prestashop.adapter.mailing_information' shared service.
     *
     * @return \PrestaShop\PrestaShop\Adapter\Mail\MailingInformation
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.adapter.mailing_information'] = new \PrestaShop\PrestaShop\Adapter\Mail\MailingInformation();
    }
}
