<?php

namespace ContainerIwDR3j7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSetSuppliersHandlerService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PrestaShop\PrestaShop\Adapter\Product\Supplier\CommandHandler\SetSuppliersHandler' shared service.
     *
     * @return \PrestaShop\PrestaShop\Adapter\Product\Supplier\CommandHandler\SetSuppliersHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['PrestaShop\\PrestaShop\\Adapter\\Product\\Supplier\\CommandHandler\\SetSuppliersHandler'] = new \PrestaShop\PrestaShop\Adapter\Product\Supplier\CommandHandler\SetSuppliersHandler(($container->privates['PrestaShop\\PrestaShop\\Adapter\\Product\\Update\\ProductSupplierUpdater'] ?? $container->load('getProductSupplierUpdaterService')));
    }
}
