<?php

namespace ContainerIwDR3j7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecuredFileReaderControllerService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PrestaShopBundle\Controller\Admin\SecuredFileReaderController' shared service.
     *
     * @return \PrestaShopBundle\Controller\Admin\SecuredFileReaderController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['PrestaShopBundle\\Controller\\Admin\\SecuredFileReaderController'] = new \PrestaShopBundle\Controller\Admin\SecuredFileReaderController((\dirname(__DIR__, 5).'/upload/'));
    }
}
