<?php

namespace ContainerXrLzW05;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_LRqCPotService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.messenger.handler_descriptor.lRqCPot' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.messenger.handler_descriptor.lRqCPot'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(($container->services['prestashop.core.domain.theme.command_handler.import_theme_handler'] ?? $container->load('getPrestashop_Core_Domain_Theme_CommandHandler_ImportThemeHandlerService'))->handle(...), ['method' => 'handle']);
    }
}
