<?php

namespace ContainerXrLzW05;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_Oh3b0GFService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.messenger.handler_descriptor.Oh3b0GF' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.messenger.handler_descriptor.Oh3b0GF'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(($container->services['prestashop.adapter.supplier.command_handler.delete_supplier_handler'] ?? $container->load('getPrestashop_Adapter_Supplier_CommandHandler_DeleteSupplierHandlerService'))->handle(...), ['method' => 'handle']);
    }
}
