<?php

namespace ContainerXrLzW05;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9LBAFaYService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.9LBAFaY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9LBAFaY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'orderReturnStatesFilters' => ['privates', '.errored..service_locator.9LBAFaY.PrestaShop\\PrestaShop\\Core\\Search\\Filters\\OrderReturnStatesFilters', NULL, 'Cannot autowire service ".service_locator.9LBAFaY": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\OrderReturnStatesFilters" but no such service exists.'],
            'orderReturnStatesGridFactory' => ['services', 'prestashop.core.grid.factory.order_return_states', 'getPrestashop_Core_Grid_Factory_OrderReturnStatesService', true],
            'orderStatesFilters' => ['privates', '.errored..service_locator.9LBAFaY.PrestaShop\\PrestaShop\\Core\\Search\\Filters\\OrderStatesFilters', NULL, 'Cannot autowire service ".service_locator.9LBAFaY": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\OrderStatesFilters" but no such service exists.'],
            'orderStatesGridFactory' => ['services', 'prestashop.core.grid.factory.order_states', 'getPrestashop_Core_Grid_Factory_OrderStatesService', true],
        ], [
            'orderReturnStatesFilters' => 'PrestaShop\\PrestaShop\\Core\\Search\\Filters\\OrderReturnStatesFilters',
            'orderReturnStatesGridFactory' => 'PrestaShop\\PrestaShop\\Core\\Grid\\GridFactoryInterface',
            'orderStatesFilters' => 'PrestaShop\\PrestaShop\\Core\\Search\\Filters\\OrderStatesFilters',
            'orderStatesGridFactory' => 'PrestaShop\\PrestaShop\\Core\\Grid\\GridFactoryInterface',
        ]);
    }
}
