<?php

namespace ContainerXrLzW05;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAccessDeniedListenerService extends AdminKernelProdContainer
{
    /*
     * Gets the private 'PrestaShopBundle\EventListener\Admin\AccessDeniedListener' shared autowired service.
     *
     * @return \PrestaShopBundle\EventListener\Admin\AccessDeniedListener
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['prestashop.router'] ?? $container->load('getPrestashop_RouterService'));

        if (isset($container->privates['PrestaShopBundle\\EventListener\\Admin\\AccessDeniedListener'])) {
            return $container->privates['PrestaShopBundle\\EventListener\\Admin\\AccessDeniedListener'];
        }

        return $container->privates['PrestaShopBundle\\EventListener\\Admin\\AccessDeniedListener'] = new \PrestaShopBundle\EventListener\Admin\AccessDeniedListener($a, ($container->services['Symfony\\Contracts\\Translation\\TranslatorInterface'] ?? self::getTranslatorInterfaceService($container)), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->privates['annotations.cached_reader'] ?? $container->load('getAnnotations_CachedReaderService')));
    }
}
