<?php

namespace ContainerXrLzW05;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCartRuleControllerService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PrestaShopBundle\Controller\Admin\Sell\Catalog\CartRuleController' shared autowired service.
     *
     * @return \PrestaShopBundle\Controller\Admin\Sell\Catalog\CartRuleController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['PrestaShopBundle\\Controller\\Admin\\Sell\\Catalog\\CartRuleController'] = $instance = new \PrestaShopBundle\Controller\Admin\Sell\Catalog\CartRuleController();

        $instance->setContainer(($container->privates['.service_locator.YWuqMV9'] ?? $container->load('get_ServiceLocator_YWuqMV9Service'))->withContext('PrestaShopBundle\\Controller\\Admin\\Sell\\Catalog\\CartRuleController', $container));

        return $instance;
    }
}
