<?php

namespace ContainerXrLzW05;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFooterService extends AdminKernelProdContainer
{
    /*
     * Gets the private 'PrestaShopBundle\Twig\Component\Footer' autowired service.
     *
     * @return \PrestaShopBundle\Twig\Component\Footer
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->factories['service_container']['PrestaShopBundle\\Twig\\Component\\Footer'] = function ($container) {
            return new \PrestaShopBundle\Twig\Component\Footer();
        };

        return $container->factories['service_container']['PrestaShopBundle\\Twig\\Component\\Footer']($container);
    }
}
