<?php

namespace ContainerXrLzW05;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImageSettingsControllerService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PrestaShopBundle\Controller\Admin\Improve\Design\ImageSettingsController' shared autowired service.
     *
     * @return \PrestaShopBundle\Controller\Admin\Improve\Design\ImageSettingsController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['PrestaShopBundle\\Controller\\Admin\\Improve\\Design\\ImageSettingsController'] = $instance = new \PrestaShopBundle\Controller\Admin\Improve\Design\ImageSettingsController();

        $instance->setContainer(($container->privates['.service_locator.YWuqMV9'] ?? $container->load('get_ServiceLocator_YWuqMV9Service'))->withContext('PrestaShopBundle\\Controller\\Admin\\Improve\\Design\\ImageSettingsController', $container));

        return $instance;
    }
}
