<?php

namespace ContainerXrLzW05;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMetaFiltersService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.Zl1wgB1.PrestaShop\PrestaShop\Core\Search\Filters\MetaFilters' shared service.
     *
     * @return \PrestaShop\PrestaShop\Core\Search\Filters\MetaFilters
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Zl1wgB1": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\MetaFilters" but no such service exists.');
    }
}
