<?php

namespace ContainerXrLzW05;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMultistoreHeaderService extends AdminKernelProdContainer
{
    /*
     * Gets the private 'PrestaShopBundle\Twig\Component\MultistoreHeader' autowired service.
     *
     * @return \PrestaShopBundle\Twig\Component\MultistoreHeader
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->factories['service_container']['PrestaShopBundle\\Twig\\Component\\MultistoreHeader'] = function ($container) {
            $a = ($container->privates['PrestaShopBundle\\Twig\\Layout\\MenuBuilder'] ?? self::getMenuBuilderService($container));

            if (isset($container->privates['PrestaShopBundle\\Twig\\Component\\MultistoreHeader'])) {
                return $container->privates['PrestaShopBundle\\Twig\\Component\\MultistoreHeader'];
            }

            return new \PrestaShopBundle\Twig\Component\MultistoreHeader($a, $container->parameters['prestashop.controllers_all_shop_context'], ($container->privates['PrestaShop\\PrestaShop\\Core\\Context\\ShopContext'] ?? self::getShopContext2Service($container)), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->services['Symfony\\Contracts\\Translation\\TranslatorInterface'] ?? self::getTranslatorInterfaceService($container)), ($container->services['PrestaShop\\PrestaShop\\Core\\Util\\ColorBrightnessCalculator'] ??= new \PrestaShop\PrestaShop\Core\Util\ColorBrightnessCalculator()), ($container->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? self::getLegacyContextService($container)), ($container->privates['PrestaShop\\PrestaShop\\Core\\Context\\EmployeeContext'] ?? self::getEmployeeContextService($container)));
        };

        return $container->factories['service_container']['PrestaShopBundle\\Twig\\Component\\MultistoreHeader']($container);
    }
}
