<?php

namespace ContainerXrLzW05;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderPaymentTypeService extends AdminKernelProdContainer
{
    /*
     * Gets the private 'PrestaShopBundle\Form\Admin\Sell\Order\OrderPaymentType' shared autowired service.
     *
     * @return \PrestaShopBundle\Form\Admin\Sell\Order\OrderPaymentType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['PrestaShopBundle\\Form\\Admin\\Sell\\Order\\OrderPaymentType'] = new \PrestaShopBundle\Form\Admin\Sell\Order\OrderPaymentType(($container->services['Symfony\\Contracts\\Translation\\TranslatorInterface'] ?? self::getTranslatorInterfaceService($container)), ($container->services['prestashop.adapter.form.choice_provider.currency_symbol_by_id'] ??= new \PrestaShop\PrestaShop\Adapter\Form\ChoiceProvider\CurrencySymbolByIdChoiceProvider()), ($container->services['prestashop.adapter.form.choice_provider.order_invoice_by_id'] ?? $container->load('getPrestashop_Adapter_Form_ChoiceProvider_OrderInvoiceByIdService')), ($container->services['prestashop.adapter.form.choice_provider.installed_payment_modules'] ??= new \PrestaShop\PrestaShop\Adapter\Form\ChoiceProvider\InstalledPaymentModulesChoiceProvider()), ($container->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? self::getLegacyContextService($container))->getContext()->language->id, ($container->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? self::getLegacyContextService($container))->getContext()->shop->id);
    }
}
