<?php

namespace ContainerXrLzW05;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Adapter_Profile_CommandHandler_BulkDeleteProfileService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'prestashop.adapter.profile.command_handler.bulk_delete_profile' shared service.
     *
     * @return \PrestaShop\PrestaShop\Adapter\Profile\CommandHandler\BulkDeleteProfileHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.adapter.profile.command_handler.bulk_delete_profile'] = new \PrestaShop\PrestaShop\Adapter\Profile\CommandHandler\BulkDeleteProfileHandler(($container->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] ??= new \PrestaShop\PrestaShop\Adapter\Configuration())->get("_PS_ADMIN_PROFILE_"), ($container->services['prestashop.adapter.data_provider.employee'] ?? $container->load('getPrestashop_Adapter_DataProvider_EmployeeService')));
    }
}
