<?php

namespace ContainerXrLzW05;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Translation_Factory_ProviderDefinitionService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'prestashop.translation.factory.provider_definition' shared service.
     *
     * @return \PrestaShop\PrestaShop\Core\Translation\Storage\Provider\Definition\ProviderDefinitionFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.translation.factory.provider_definition'] = new \PrestaShop\PrestaShop\Core\Translation\Storage\Provider\Definition\ProviderDefinitionFactory();
    }
}
