<?php

namespace ContainerXrLzW05;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Core_Filter_FrontEndObject_MainService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'prestashop.core.filter.front_end_object.main' shared service.
     *
     * @return \PrestaShop\PrestaShop\Core\Filter\FrontEndObject\MainFilter
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.core.filter.front_end_object.main'] = new \PrestaShop\PrestaShop\Core\Filter\FrontEndObject\MainFilter(['cart' => ($container->services['prestashop.core.filter.front_end_object.cart'] ?? $container->load('getPrestashop_Core_Filter_FrontEndObject_CartService')), 'customer' => ($container->services['prestashop.core.filter.front_end_object.customer'] ??= new \PrestaShop\PrestaShop\Core\Filter\FrontEndObject\CustomerFilter()), 'shop' => ($container->services['prestashop.core.filter.front_end_object.shop'] ??= new \PrestaShop\PrestaShop\Core\Filter\FrontEndObject\ShopFilter()), 'configuration' => ($container->services['prestashop.core.filter.front_end_object.configuration'] ??= new \PrestaShop\PrestaShop\Core\Filter\FrontEndObject\ConfigurationFilter())]);
    }
}
