<?php

namespace ContainerXrLzW05;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Adapter_Localization_ConfigurationService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'prestashop.adapter.localization.configuration' shared service.
     *
     * @return \PrestaShop\PrestaShop\Adapter\Localization\LocalizationConfiguration
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.adapter.localization.configuration'] = new \PrestaShop\PrestaShop\Adapter\Localization\LocalizationConfiguration(($container->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] ??= new \PrestaShop\PrestaShop\Adapter\Configuration()), ($container->services['prestashop.adapter.language.activator'] ??= new \PrestaShop\PrestaShop\Adapter\Language\LanguageActivator()), ($container->services['prestashop.adapter.manager.currency'] ??= new \PrestaShop\PrestaShop\Adapter\Currency\CurrencyManager()));
    }
}
