<?php

namespace ContainerXrLzW05;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Adapter_LegacyContextLoaderService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'prestashop.adapter.legacy_context_loader' shared service.
     *
     * @return \PrestaShop\PrestaShop\Adapter\LegacyContextLoader
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.adapter.legacy_context_loader'] = new \PrestaShop\PrestaShop\Adapter\LegacyContextLoader(($container->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? self::getLegacyContextService($container))->getContext());
    }
}
