<?php

namespace ContainerXrLzW05;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Translation_Theme_ExporterService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'prestashop.translation.theme.exporter' shared service.
     *
     * @return \PrestaShopBundle\Translation\Exporter\ThemeExporter
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['prestashop.translation.theme.exporter'] = $instance = new \PrestaShopBundle\Translation\Exporter\ThemeExporter(($container->services['prestashop.translation.theme_extractor'] ?? $container->load('getPrestashop_Translation_ThemeExtractorService')), ($container->services['prestashop.translation.theme_provider'] ?? $container->load('getPrestashop_Translation_ThemeProviderService')), ($container->services['prestashop.core.addon.theme.repository'] ?? $container->load('getPrestashop_Core_Addon_Theme_RepositoryService')), ($container->services['prestashop.translation.dumper.xliff'] ??= new \PrestaShop\TranslationToolsBundle\Translation\Dumper\XliffFileDumper()), ($container->services['prestashop.utils.zip_manager'] ??= new \PrestaShopBundle\Utils\ZipManager()), ($container->privates['filesystem'] ??= new \Symfony\Component\Filesystem\Filesystem()));

        $instance->cacheDir = $container->targetDir.'';
        $instance->setExportDir(($container->targetDir.''.'/export'));

        return $instance;
    }
}
