<?php

namespace ContainerXrLzW05;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Adapter_OrderReturnState_Repository_OrderReturnStateRepositoryService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'prestashop.adapter.order_return_state.repository.order_return_state_repository' shared service.
     *
     * @return \PrestaShop\PrestaShop\Adapter\OrderReturnState\Repository\OrderReturnStateRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.adapter.order_return_state.repository.order_return_state_repository'] = new \PrestaShop\PrestaShop\Adapter\OrderReturnState\Repository\OrderReturnStateRepository();
    }
}
