<?php

namespace ContainerXrLzW05;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Admin_TrafficSeo_MetaSettings_ShopUrls_FormDataProviderService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'prestashop.admin.traffic_seo.meta_settings.shop_urls.form_data_provider' shared service.
     *
     * @return \PrestaShopBundle\Form\Admin\Configure\ShopParameters\TrafficSeo\Meta\MetaSettingsShopUrlsFormDataProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.admin.traffic_seo.meta_settings.shop_urls.form_data_provider'] = new \PrestaShopBundle\Form\Admin\Configure\ShopParameters\TrafficSeo\Meta\MetaSettingsShopUrlsFormDataProvider(($container->services['prestashop.adapter.meta.shop_url.configuration'] ?? $container->load('getPrestashop_Adapter_Meta_ShopUrl_ConfigurationService')), ($container->services['Symfony\\Contracts\\Translation\\TranslatorInterface'] ?? self::getTranslatorInterfaceService($container)), ($container->services['prestashop.adapter.validate'] ??= new \PrestaShop\PrestaShop\Adapter\Validate()));
    }
}
