<?php

namespace ContainerMuK0XhM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_FExxK1Service extends AdminKernelDevDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.FExx_k1' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.messenger.handler_descriptor.FExx_k1'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(($container->services['prestashop.adapter.configuration.command_handler.switch_debug_mode_handler'] ?? $container->load('getPrestashop_Adapter_Configuration_CommandHandler_SwitchDebugModeHandlerService'))->handle(...), ['method' => 'handle']);
    }
}
