<?php

namespace ContainerMuK0XhM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Container_Private_Prestashop_Core_Localization_Pack_Loader_LocalService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the public '.container.private.prestashop.core.localization.pack.loader.local' shared autowired service.
     *
     * @return \PrestaShop\PrestaShop\Core\Localization\Pack\Loader\LocalLocalizationPackLoader
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['.container.private.prestashop.core.localization.pack.loader.local'] = new \PrestaShop\PrestaShop\Core\Localization\Pack\Loader\LocalLocalizationPackLoader(($container->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] ??= new \PrestaShop\PrestaShop\Adapter\Configuration()));
    }
}
