<?php

namespace ContainerMuK0XhM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_3cqtQdAService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.3cqtQdA' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.messenger.handler_descriptor.3cqtQdA'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(($container->services['prestashop.adapter.supplier.query_handler.get_supplier_for_editing'] ?? $container->load('getPrestashop_Adapter_Supplier_QueryHandler_GetSupplierForEditingService'))->handle(...), ['method' => 'handle']);
    }
}
