<?php

namespace ContainerMuK0XhM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Qr8Vp91Service extends AdminKernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Qr8Vp91' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Qr8Vp91'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'formBuilder' => ['services', 'prestashop.core.form.identifiable_object.builder.manufacturer_form_builder', 'getPrestashop_Core_Form_IdentifiableObject_Builder_ManufacturerFormBuilderService', true],
            'formHandler' => ['services', 'prestashop.core.form.identifiable_object.handler.manufacturer_form_handler', 'getPrestashop_Core_Form_IdentifiableObject_Handler_ManufacturerFormHandlerService', true],
        ], [
            'formBuilder' => 'PrestaShop\\PrestaShop\\Core\\Form\\IdentifiableObject\\Builder\\FormBuilderInterface',
            'formHandler' => 'PrestaShop\\PrestaShop\\Core\\Form\\IdentifiableObject\\Handler\\FormHandlerInterface',
        ]);
    }
}
