<?php

namespace ContainerMuK0XhM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Container_Private_Form_Extension_MultistoreDropdownService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the public '.container.private.form.extension.multistore_dropdown' shared autowired service.
     *
     * @return \PrestaShopBundle\Form\Extension\MultistoreExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['.container.private.form.extension.multistore_dropdown'] = new \PrestaShopBundle\Form\Extension\MultistoreExtension();
    }
}
