<?php

namespace ContainerMuK0XhM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Container_Private_Prestashop_Bundle_Form_DataTransformer_ArabicToLatinDigitService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the public '.container.private.prestashop.bundle.form.data_transformer.arabic_to_latin_digit' shared autowired service.
     *
     * @return \PrestaShopBundle\Form\DataTransformer\ArabicToLatinDigitDataTransformer
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['.container.private.prestashop.bundle.form.data_transformer.arabic_to_latin_digit'] = new \PrestaShopBundle\Form\DataTransformer\ArabicToLatinDigitDataTransformer(($container->privates['PrestaShop\\PrestaShop\\Core\\Util\\ArabicToLatinDigitConverter'] ??= new \PrestaShop\PrestaShop\Core\Util\ArabicToLatinDigitConverter()));
    }
}
