<?php

namespace ContainerMuK0XhM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KdRZt6Service extends AdminKernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KdR_Zt6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KdR_Zt6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'moduleRepository' => ['privates', 'PrestaShop\\PrestaShop\\Adapter\\Module\\Repository\\ModuleRepository', 'getModuleRepository3Service', true],
        ], [
            'moduleRepository' => 'PrestaShop\\PrestaShop\\Adapter\\Module\\Repository\\ModuleRepository',
        ]);
    }
}
