<?php

namespace ContainerMuK0XhM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_R7jABp8Service extends AdminKernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.r7jABp8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.r7jABp8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'catalogPriceRuleFilters' => ['privates', '.errored..service_locator.r7jABp8.PrestaShop\\PrestaShop\\Core\\Search\\Filters\\CatalogPriceRuleFilters', NULL, 'Cannot autowire service ".service_locator.r7jABp8": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\CatalogPriceRuleFilters" but no such service exists.'],
            'gridFactory' => ['services', 'prestashop.core.grid.grid_factory.catalog_price_rule', 'getPrestashop_Core_Grid_GridFactory_CatalogPriceRuleService', true],
        ], [
            'catalogPriceRuleFilters' => 'PrestaShop\\PrestaShop\\Core\\Search\\Filters\\CatalogPriceRuleFilters',
            'gridFactory' => 'PrestaShop\\PrestaShop\\Core\\Grid\\GridFactoryInterface',
        ]);
    }
}
