<?php

namespace ContainerMuK0XhM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoriesProviderService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the public 'PrestaShopBundle\Service\DataProvider\Admin\CategoriesProvider' shared service.
     *
     * @return \PrestaShopBundle\Service\DataProvider\Admin\CategoriesProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        if (true === $lazyLoad) {
            return $container->services['PrestaShopBundle\\Service\\DataProvider\\Admin\\CategoriesProvider'] = $container->createProxy('CategoriesProviderProxy7ff07d9', static fn () => \CategoriesProviderProxy7ff07d9::createLazyProxy(static fn () => self::do($container, false)));
        }

        return ($container->services['PrestaShop\\PrestaShop\\Adapter\\Category\\CategoriesProviderBuilder'] ?? $container->load('getCategoriesProviderBuilderService'))->build();
    }
}
