<?php

namespace ContainerMuK0XhM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDecimalNumberTypeExtractorService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the private 'PrestaShopBundle\ApiPlatform\Serializer\DecimalNumberTypeExtractor' shared autowired service.
     *
     * @return \PrestaShopBundle\ApiPlatform\Serializer\DecimalNumberTypeExtractor
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['PrestaShopBundle\\ApiPlatform\\Serializer\\DecimalNumberTypeExtractor'] = new \PrestaShopBundle\ApiPlatform\Serializer\DecimalNumberTypeExtractor(($container->privates['api_platform.serializer.mapping.class_metadata_factory'] ?? self::getApiPlatform_Serializer_Mapping_ClassMetadataFactoryService($container)));
    }
}
