<?php

namespace ContainerMuK0XhM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGenerateByDateTypeService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the private 'PrestaShopBundle\Form\Admin\Sell\Order\Invoices\GenerateByDateType' shared autowired service.
     *
     * @return \PrestaShopBundle\Form\Admin\Sell\Order\Invoices\GenerateByDateType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['PrestaShopBundle\\Form\\Admin\\Sell\\Order\\Invoices\\GenerateByDateType'] = new \PrestaShopBundle\Form\Admin\Sell\Order\Invoices\GenerateByDateType();
    }
}
