<?php

namespace ContainerMuK0XhM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Adapter_Customer_CustomerDataSourceService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the public 'prestashop.adapter.customer.customer_data_source' shared service.
     *
     * @return \PrestaShop\PrestaShop\Adapter\Customer\CustomerDataSource
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.adapter.customer.customer_data_source'] = new \PrestaShop\PrestaShop\Adapter\Customer\CustomerDataSource();
    }
}
