<?php

namespace ContainerMuK0XhM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Core_Form_Builder_FormBuilderFactoryService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the public 'prestashop.core.form.builder.form_builder_factory' shared service.
     *
     * @return \PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Builder\FormBuilderFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['form.factory'] ?? $container->load('getForm_FactoryService'));

        if (isset($container->services['prestashop.core.form.builder.form_builder_factory'])) {
            return $container->services['prestashop.core.form.builder.form_builder_factory'];
        }
        $b = ($container->privates['form.registry'] ?? $container->load('getForm_RegistryService'));

        if (isset($container->services['prestashop.core.form.builder.form_builder_factory'])) {
            return $container->services['prestashop.core.form.builder.form_builder_factory'];
        }

        return $container->services['prestashop.core.form.builder.form_builder_factory'] = new \PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Builder\FormBuilderFactory($a, ($container->services['PrestaShop\\PrestaShop\\Core\\Hook\\HookDispatcher'] ?? self::getHookDispatcherService($container)), $b);
    }
}
