<?php

namespace ContainerMuK0XhM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Adapter_Pdf_Generator_CreditSlipService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the public 'prestashop.adapter.pdf.generator.credit_slip' shared service.
     *
     * @return \PrestaShop\PrestaShop\Adapter\PDF\PDFGenerator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.adapter.pdf.generator.credit_slip'] = new \PrestaShop\PrestaShop\Adapter\PDF\PDFGenerator(($container->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? self::getLegacyContextService($container))->getSmarty(), ($container->services['prestashop.adapter.pdf.type_provider.credit_slip'] ??= new \PrestaShop\PrestaShop\Adapter\CreditSlip\CreditSlipTemplateTypeProvider()));
    }
}
