<?php

namespace ContainerMuK0XhM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Adapter_Order_QueryHandler_GetOrderPreviewHandlerService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the public 'prestashop.adapter.order.query_handler.get_order_preview_handler' shared service.
     *
     * @return \PrestaShop\PrestaShop\Adapter\Order\QueryHandler\GetOrderPreviewHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.adapter.order.query_handler.get_order_preview_handler'] = new \PrestaShop\PrestaShop\Adapter\Order\QueryHandler\GetOrderPreviewHandler(($container->services['PrestaShop\\PrestaShop\\Core\\Localization\\Locale\\Repository'] ?? self::getRepositoryService($container)), ($container->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? self::getLegacyContextService($container))->getContext()->language->getLocale(), ($container->services['prestashop.adapter.address.formatter'] ??= new \PrestaShop\PrestaShop\Adapter\Address\AddressFormatter()));
    }
}
