<?php

namespace ContainerMuK0XhM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Core_Admin_UrlGeneratorService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the public 'prestashop.core.admin.url_generator' shared service.
     *
     * @return \Symfony\Component\Routing\Generator\UrlGeneratorInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.core.admin.url_generator'] = ($container->services['prestashop.core.admin.url_generator_factory'] ?? $container->load('getPrestashop_Core_Admin_UrlGeneratorFactoryService'))->forSymfony();
    }
}
