<?php

namespace ContainerMuK0XhM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Core_ShowcaseCard_CommandHandler_CloseShowcaseCardService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the public 'prestashop.core.showcase_card.command_handler.close_showcase_card' shared service.
     *
     * @return \PrestaShop\PrestaShop\Core\Domain\ShowcaseCard\CommandHandler\CloseShowcaseCardHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.core.showcase_card.command_handler.close_showcase_card'] = new \PrestaShop\PrestaShop\Core\Domain\ShowcaseCard\CommandHandler\CloseShowcaseCardHandler(($container->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] ??= new \PrestaShop\PrestaShop\Adapter\Configuration()), ($container->services['prestashop.core.showcase_card.configuration_map'] ??= new \PrestaShop\PrestaShop\Core\Domain\ShowcaseCard\ConfigurationMap()));
    }
}
