<?php

namespace ContainerMuK0XhM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductImageUploaderService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the private 'PrestaShop\PrestaShop\Adapter\Product\Image\Uploader\ProductImageUploader' shared autowired service.
     *
     * @return \PrestaShop\PrestaShop\Adapter\Product\Image\Uploader\ProductImageUploader
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['PrestaShop\\PrestaShop\\Adapter\\Product\\Image\\Uploader\\ProductImageUploader'] = new \PrestaShop\PrestaShop\Adapter\Product\Image\Uploader\ProductImageUploader(($container->services['prestashop.adapter.product.image.product_image_filesystem_path_factory'] ?? $container->load('getPrestashop_Adapter_Product_Image_ProductImageFilesystemPathFactoryService')), ($container->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? self::getLegacyContextService($container))->getContext()->shop->id, ($container->services['PrestaShop\\PrestaShop\\Adapter\\Image\\ImageGenerator'] ?? $container->load('getImageGeneratorService')), ($container->services['PrestaShop\\PrestaShop\\Core\\Hook\\HookDispatcher'] ?? self::getHookDispatcherService($container)), ($container->services['PrestaShop\\PrestaShop\\Adapter\\Product\\Image\\Repository\\ProductImageRepository'] ?? $container->load('getProductImageRepositoryService')));
    }
}
