<?php

namespace ContainerMuK0XhM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Adapter_Category_CommandHandler_UpdateCategoryPositionHandlerService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the public 'prestashop.adapter.category.command_handler.update_category_position_handler' shared service.
     *
     * @return \PrestaShop\PrestaShop\Adapter\Category\CommandHandler\UpdateCategoryPositionHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.adapter.category.command_handler.update_category_position_handler'] = new \PrestaShop\PrestaShop\Adapter\Category\CommandHandler\UpdateCategoryPositionHandler();
    }
}
