<?php

namespace ContainerMuK0XhM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Admin_Order_Invoices_ByDate_DataProviderService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the public 'prestashop.admin.order.invoices.by_date.data_provider' shared service.
     *
     * @return \PrestaShopBundle\Form\Admin\Sell\Order\Invoices\InvoicesByDateDataProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.admin.order.invoices.by_date.data_provider'] = new \PrestaShopBundle\Form\Admin\Sell\Order\Invoices\InvoicesByDateDataProvider(($container->services['prestashop.adapter.data_provider.order_invoice'] ??= new \PrestaShop\PrestaShop\Adapter\Invoice\OrderInvoiceDataProvider()));
    }
}
