<?php

namespace ContainerMuK0XhM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getZipSourceHandlerService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the public 'PrestaShop\PrestaShop\Core\Module\SourceHandler\ZipSourceHandler' shared autowired service.
     *
     * @return \PrestaShop\PrestaShop\Core\Module\SourceHandler\ZipSourceHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['PrestaShop\\PrestaShop\\Core\\Module\\SourceHandler\\ZipSourceHandler'] = new \PrestaShop\PrestaShop\Core\Module\SourceHandler\ZipSourceHandler((\dirname(__DIR__, 5).'/modules/'), ($container->services['Symfony\\Contracts\\Translation\\TranslatorInterface'] ?? self::getTranslatorInterfaceService($container)));
    }
}
