<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXrLzW05\AdminKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXrLzW05/AdminKernelProdContainer.php') {
    touch(__DIR__.'/ContainerXrLzW05.legacy');

    return;
}

if (!\class_exists(AdminKernelProdContainer::class, false)) {
    \class_alias(\ContainerXrLzW05\AdminKernelProdContainer::class, AdminKernelProdContainer::class, false);
}

return new \ContainerXrLzW05\AdminKernelProdContainer([
    'container.build_hash' => 'XrLzW05',
    'container.build_id' => '879d0aa9',
    'container.build_time' => 1749907790,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXrLzW05');
