<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\PrestaShop\Core\Security\TokenAuthenticator' shared service.

return $this->privates['PrestaShop\\PrestaShop\\Core\\Security\\TokenAuthenticator'] = new \PrestaShop\PrestaShop\Core\Security\TokenAuthenticator(new \PrestaShopBundle\Security\OAuth2\ResourceServer(new \League\OAuth2\Server\ResourceServer(($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] ?? ($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] = new \PrestaShopBundle\Security\OAuth2\Repository\AccessTokenRepository())), new \League\OAuth2\Server\CryptKey('-----BEGIN PUBLIC KEY-----'."\n".'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAodIqzMcIuUxsGjh7QhUC'."\n".'jygsQB9viI+5ASJZFDxxyq05GjzsMQmlp23q9NJgF77m+3CvU1SKThhHVUwNqrM/'."\n".'qZF2zXur+19wBzbVy9Qcf6WvAjIiezDuyv2L5oxJaLO/y3/Yz/hZakBjAJInwI9C'."\n".'NmqsPEM9qpk4BePVyLejiUEmw2JA5SV1WmHXaMZTbXL54yLXmO9jE5cLiQdNG6r2'."\n".'P3nmpxIl1gOx0SIRIZNQAi43w+vgNgds/P2kJQ0CmenLhu/mqQthUMe+RvP4wBV/'."\n".'YiemHy5cjAZ6hFbuJwo4VTrLOL2OHuFUP7rqTS0XhJzDZuWX/DZazz2Qt3cf2O4T'."\n".'YwIDAQAB'."\n".'-----END PUBLIC KEY-----'."\n".'')), ($this->privates['security.user.provider.concrete.oauth2'] ?? ($this->privates['security.user.provider.concrete.oauth2'] = new \Symfony\Component\Security\Core\User\InMemoryUserProvider([])))), ($this->privates['Symfony\\Bridge\\PsrHttpMessage\\Factory\\PsrHttpFactory'] ?? $this->load('getPsrHttpFactoryService.php')));
