<?php

namespace ContainerMuK0XhM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_OPECpi7Service extends AdminKernelDevDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.oPECpi7' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.messenger.handler_descriptor.oPECpi7'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(($container->services['prestashop.adapter.cms_page.command_handler.add_cms_page_category_handler'] ?? $container->load('getPrestashop_Adapter_CmsPage_CommandHandler_AddCmsPageCategoryHandlerService'))->handle(...), ['method' => 'handle']);
    }
}
