<?php

namespace ContainerMuK0XhM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ab5fFjdService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ab5fFjd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ab5fFjd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'contactFormBuilder' => ['services', 'prestashop.core.form.identifiable_object.builder.contact_form_builder', 'getPrestashop_Core_Form_IdentifiableObject_Builder_ContactFormBuilderService', true],
            'contactFormHandler' => ['services', 'prestashop.core.form.identifiable_object.handler.contact_form_handler', 'getPrestashop_Core_Form_IdentifiableObject_Handler_ContactFormHandlerService', true],
        ], [
            'contactFormBuilder' => 'PrestaShop\\PrestaShop\\Core\\Form\\IdentifiableObject\\Builder\\FormBuilderInterface',
            'contactFormHandler' => 'PrestaShop\\PrestaShop\\Core\\Form\\IdentifiableObject\\Handler\\FormHandlerInterface',
        ]);
    }
}
