<?php

namespace ContainerMuK0XhM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Container_Private_Prestashop_Core_Form_ChoiceProvider_NonInstalledLocalizationService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the public '.container.private.prestashop.core.form.choice_provider.non_installed_localization' shared autowired service.
     *
     * @return \PrestaShop\PrestaShop\Core\Form\ChoiceProvider\NonInstalledLocalizationChoiceProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['.container.private.prestashop.core.form.choice_provider.non_installed_localization'] = new \PrestaShop\PrestaShop\Core\Form\ChoiceProvider\NonInstalledLocalizationChoiceProvider(($container->services['prestashop.core.language.pack.loader.remote'] ?? $container->load('getPrestashop_Core_Language_Pack_Loader_RemoteService'))->getLanguagePackList(), ($container->services['prestashop.adapter.language.validator'] ??= new \PrestaShop\PrestaShop\Adapter\Language\LanguageValidator()), ($container->services['prestashop.adapter.data_provider.language'] ??= new \PrestaShop\PrestaShop\Adapter\Language\LanguageDataProvider()));
    }
}
