<?php

namespace ContainerMuK0XhM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_STkH9WJService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.sTkH9WJ' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.messenger.handler_descriptor.sTkH9WJ'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(($container->services['prestashop.adapter.currency.command_handler.update_exchange_rates'] ??= new \PrestaShop\PrestaShop\Adapter\Currency\CommandHandler\RefreshExchangeRatesHandler())->handle(...), ['method' => 'handle']);
    }
}
