<?php

namespace ContainerMuK0XhM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IUw_EkeService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iUw.eke' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iUw.eke'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'positionDefinition' => ['services', 'prestashop.core.grid.cms_page.position_definition', 'getPrestashop_Core_Grid_CmsPage_PositionDefinitionService', true],
        ], [
            'positionDefinition' => 'PrestaShop\\PrestaShop\\Core\\Grid\\Position\\PositionDefinition',
        ]);
    }
}
