<?php

namespace ContainerMuK0XhM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAPIClientCommand_LazyService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the private '.PrestaShopBundle\Command\APIClientCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.PrestaShopBundle\\Command\\APIClientCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('prestashop:api-client', [], 'Manage API Client.', false, #[\Closure(name: 'PrestaShopBundle\\Command\\APIClientCommand')] fn (): \PrestaShopBundle\Command\APIClientCommand => ($container->services['PrestaShopBundle\\Command\\APIClientCommand'] ?? $container->load('getAPIClientCommandService')));
    }
}
