<?php

namespace ContainerMuK0XhM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminAuthenticationSuccessHandlerService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the public 'PrestaShopBundle\Security\Admin\AdminAuthenticationSuccessHandler' shared autowired service.
     *
     * @return \PrestaShopBundle\Security\Admin\AdminAuthenticationSuccessHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['PrestaShopBundle\\Security\\Admin\\AdminAuthenticationSuccessHandler'] = new \PrestaShopBundle\Security\Admin\AdminAuthenticationSuccessHandler(($container->services['PrestaShopBundle\\Security\\Admin\\EmployeeHomepageProvider'] ?? $container->load('getEmployeeHomepageProviderService')), ($container->services['prestashop.router'] ?? $container->load('getPrestashop_RouterService')));
    }
}
