<?php

namespace ContainerMuK0XhM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCarrierBuilderService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the public 'PrestaShop\Module\PsxMarketingWithGoogle\Builder\CarrierBuilder' shared service.
     *
     * @return \PrestaShop\Module\PsxMarketingWithGoogle\Builder\CarrierBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['PrestaShop\\Module\\PsxMarketingWithGoogle\\Builder\\CarrierBuilder'] = new \PrestaShop\Module\PsxMarketingWithGoogle\Builder\CarrierBuilder(($container->services['PrestaShop\\Module\\PsxMarketingWithGoogle\\Repository\\CarrierRepository'] ??= new \PrestaShop\Module\PsxMarketingWithGoogle\Repository\CarrierRepository()), ($container->services['PrestaShop\\Module\\PsxMarketingWithGoogle\\Repository\\CountryRepository'] ?? $container->load('getCountryRepository3Service')), ($container->services['PrestaShop\\Module\\PsxMarketingWithGoogle\\Repository\\StateRepository'] ?? $container->load('getStateRepositoryService')), ($container->services['PrestaShop\\Module\\PsxMarketingWithGoogle\\Repository\\TaxRepository'] ?? $container->load('getTaxRepositoryService')), ($container->services['PrestaShop\\Module\\PsxMarketingWithGoogle\\Adapter\\ConfigurationAdapter'] ?? $container->load('getConfigurationAdapter2Service')));
    }
}
