<?php

namespace ContainerMuK0XhM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExternalContentProviderService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the public 'PrestaShop\Module\Mbo\Service\ExternalContentProvider\ExternalContentProvider' shared autowired service.
     *
     * @return \PrestaShop\Module\Mbo\Service\ExternalContentProvider\ExternalContentProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['PrestaShop\\Module\\Mbo\\Service\\ExternalContentProvider\\ExternalContentProvider'] = new \PrestaShop\Module\Mbo\Service\ExternalContentProvider\ExternalContentProvider();
    }
}
