<?php

namespace ContainerMuK0XhM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getForwardCustomerThreadTypeService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the private 'PrestaShopBundle\Form\Admin\CustomerService\CustomerThread\ForwardCustomerThreadType' shared autowired service.
     *
     * @return \PrestaShopBundle\Form\Admin\CustomerService\CustomerThread\ForwardCustomerThreadType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['PrestaShopBundle\\Form\\Admin\\CustomerService\\CustomerThread\\ForwardCustomerThreadType'] = new \PrestaShopBundle\Form\Admin\CustomerService\CustomerThread\ForwardCustomerThreadType(($container->services['Symfony\\Contracts\\Translation\\TranslatorInterface'] ?? self::getTranslatorInterfaceService($container)), ($container->services['prestashop.adapter.form.choice_provider.employee_name_by_id'] ??= new \PrestaShop\PrestaShop\Adapter\Form\ChoiceProvider\EmployeeNameByIdChoiceProvider()));
    }
}
