<?php

namespace ContainerMuK0XhM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLinksProviderService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the public 'PrestaShop\Module\Mbo\Addons\Provider\LinksProvider' shared autowired service.
     *
     * @return \PrestaShop\Module\Mbo\Addons\Provider\LinksProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['prestashop.router'] ?? $container->load('getPrestashop_RouterService'));

        if (isset($container->services['PrestaShop\\Module\\Mbo\\Addons\\Provider\\LinksProvider'])) {
            return $container->services['PrestaShop\\Module\\Mbo\\Addons\\Provider\\LinksProvider'];
        }

        return $container->services['PrestaShop\\Module\\Mbo\\Addons\\Provider\\LinksProvider'] = new \PrestaShop\Module\Mbo\Addons\Provider\LinksProvider(($container->services['.container.private.prestashop.core.foundation.version'] ?? self::get_Container_Private_Prestashop_Core_Foundation_VersionService($container)), ($container->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? self::getLegacyContextService($container)), ($container->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] ??= new \PrestaShop\PrestaShop\Adapter\Configuration()), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->services['PrestaShopBundle\\Service\\DataProvider\\Admin\\CategoriesProvider'] ?? $container->load('getCategoriesProviderService')), ($container->services['Symfony\\Contracts\\Translation\\TranslatorInterface'] ?? self::getTranslatorInterfaceService($container)), $a);
    }
}
