<?php

namespace ContainerMuK0XhM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLegacySearchFormService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the private 'PrestaShopBundle\Twig\Component\Legacy\LegacySearchForm' autowired service.
     *
     * @return \PrestaShopBundle\Twig\Component\Legacy\LegacySearchForm
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->factories['service_container']['PrestaShopBundle\\Twig\\Component\\Legacy\\LegacySearchForm'] = function ($container) {
            return new \PrestaShopBundle\Twig\Component\Legacy\LegacySearchForm(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));
        };

        return $container->factories['service_container']['PrestaShopBundle\\Twig\\Component\\Legacy\\LegacySearchForm']($container);
    }
}
