<?php

namespace ContainerMuK0XhM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLegacyLinkBlockCacheService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the private 'PrestaShop\Module\LinkList\Cache\LegacyLinkBlockCache' shared autowired service.
     *
     * @return \PrestaShop\Module\LinkList\Cache\LegacyLinkBlockCache
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['PrestaShop\\Module\\LinkList\\Cache\\LegacyLinkBlockCache'] = new \PrestaShop\Module\LinkList\Cache\LegacyLinkBlockCache();
    }
}
