<?php

namespace ContainerMuK0XhM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Core_Form_IdentifiableObject_Builder_ApiClientFormBuilderService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the public 'prestashop.core.form.identifiable_object.builder.api_client_form_builder' shared service.
     *
     * @return \PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Builder\FormBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['prestashop.core.query_bus'] ?? $container->load('getPrestashop_Core_QueryBusService'));

        if (isset($container->services['prestashop.core.form.identifiable_object.builder.api_client_form_builder'])) {
            return $container->services['prestashop.core.form.identifiable_object.builder.api_client_form_builder'];
        }
        $b = ($container->services['prestashop.core.form.builder.form_builder_factory'] ?? $container->load('getPrestashop_Core_Form_Builder_FormBuilderFactoryService'));

        if (isset($container->services['prestashop.core.form.identifiable_object.builder.api_client_form_builder'])) {
            return $container->services['prestashop.core.form.identifiable_object.builder.api_client_form_builder'];
        }

        return $container->services['prestashop.core.form.identifiable_object.builder.api_client_form_builder'] = $b->create('PrestaShopBundle\\Form\\Admin\\AdvancedParameters\\AdminAPI\\ApiClientType', new \PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataProvider\ApiClientFormDataProvider($a));
    }
}
