<?php

namespace ContainerMuK0XhM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Core_Import_FieldsProvider_AddressService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the public 'prestashop.core.import.fields_provider.address' shared service.
     *
     * @return \PrestaShop\PrestaShop\Core\Import\EntityField\Provider\AddressFieldsProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.core.import.fields_provider.address'] = new \PrestaShop\PrestaShop\Core\Import\EntityField\Provider\AddressFieldsProvider(($container->services['Symfony\\Contracts\\Translation\\TranslatorInterface'] ?? self::getTranslatorInterfaceService($container)));
    }
}
