<?php

namespace ContainerMuK0XhM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Core_Form_IdentifiableObject_Builder_CarrierFormBuilderService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the public 'prestashop.core.form.identifiable_object.builder.carrier_form_builder' shared service.
     *
     * @return \PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Builder\FormBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['prestashop.core.query_bus'] ?? $container->load('getPrestashop_Core_QueryBusService'));

        if (isset($container->services['prestashop.core.form.identifiable_object.builder.carrier_form_builder'])) {
            return $container->services['prestashop.core.form.identifiable_object.builder.carrier_form_builder'];
        }

        return $container->services['prestashop.core.form.identifiable_object.builder.carrier_form_builder'] = ($container->services['prestashop.core.form.builder.form_builder_factory'] ?? $container->load('getPrestashop_Core_Form_Builder_FormBuilderFactoryService'))->create('PrestaShopBundle\\Form\\Admin\\Improve\\Shipping\\Carrier\\CarrierType', new \PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataProvider\CarrierFormDataProvider($a, ($container->privates['PrestaShop\\PrestaShop\\Core\\Context\\ShopContext'] ?? self::getShopContext2Service($container)), ($container->services['PrestaShop\\PrestaShop\\Adapter\\Currency\\CurrencyDataProvider'] ?? self::getCurrencyDataProviderService($container)), ($container->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] ??= new \PrestaShop\PrestaShop\Adapter\Configuration()), ($container->services['.container.private.prestashop.core.form.choice_provider.zone_by_id'] ??= new \PrestaShop\PrestaShop\Adapter\Form\ChoiceProvider\ZoneByIdChoiceProvider()), ($container->services['PrestaShop\\PrestaShop\\Adapter\\Group\\GroupDataProvider'] ??= new \PrestaShop\PrestaShop\Adapter\Group\GroupDataProvider())));
    }
}
