<?php

namespace ContainerMuK0XhM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Adapter_Order_QueryHandler_GetOrderProductsForViewingHandlerService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the public 'prestashop.adapter.order.query_handler.get_order_products_for_viewing_handler' shared service.
     *
     * @return \PrestaShop\PrestaShop\Adapter\Order\QueryHandler\GetOrderProductsForViewingHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.adapter.order.query_handler.get_order_products_for_viewing_handler'] = new \PrestaShop\PrestaShop\Adapter\Order\QueryHandler\GetOrderProductsForViewingHandler(($container->services['prestashop.core.image.parser.image_tag_source_parser'] ??= new \PrestaShop\PrestaShop\Core\Image\Parser\ImageTagSourceParser()), ($container->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? self::getLegacyContextService($container))->getContext()->language->id, ($container->services['prestashop.core.localization.locale.context_locale'] ?? $container->load('getPrestashop_Core_Localization_Locale_ContextLocaleService')));
    }
}
