<?php

namespace ContainerMuK0XhM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Core_Grid_Factory_CreditSlipService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the public 'prestashop.core.grid.factory.credit_slip' shared service.
     *
     * @return \PrestaShop\PrestaShop\Core\Grid\GridFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['prestashop.core.grid.filter.credit_slip_form_factory'] ?? $container->load('getPrestashop_Core_Grid_Filter_CreditSlipFormFactoryService'));

        if (isset($container->services['prestashop.core.grid.factory.credit_slip'])) {
            return $container->services['prestashop.core.grid.factory.credit_slip'];
        }

        return $container->services['prestashop.core.grid.factory.credit_slip'] = new \PrestaShop\PrestaShop\Core\Grid\GridFactory(($container->services['prestashop.core.grid.definition.factory.credit_slip'] ?? $container->load('getPrestashop_Core_Grid_Definition_Factory_CreditSlipService')), ($container->services['prestashop.core.grid.data.factory.credit_slip_decorator'] ?? $container->load('getPrestashop_Core_Grid_Data_Factory_CreditSlipDecoratorService')), $a, ($container->services['PrestaShop\\PrestaShop\\Core\\Hook\\HookDispatcher'] ?? self::getHookDispatcherService($container)));
    }
}
