<?php

namespace ContainerMuK0XhM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Adapter_CartRule_QueryHandler_SearchCartRulesHandlerService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the public 'prestashop.adapter.cart_rule.query_handler.search_cart_rules_handler' shared service.
     *
     * @return \PrestaShop\PrestaShop\Adapter\CartRule\QueryHandler\SearchCartRulesHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.adapter.cart_rule.query_handler.search_cart_rules_handler'] = new \PrestaShop\PrestaShop\Adapter\CartRule\QueryHandler\SearchCartRulesHandler(($container->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? self::getLegacyContextService($container))->getContext()->language->id);
    }
}
